### ISSUE TITLE
Example Pictures in README

### ISSUE THREAD

**Issue by tallguyjenks** [Pseudonium/Obsidian_to_Anki#10]
would be helpful to see some simple/slightly complex examples of markdown syntax --> card displayed in pictures as well as written out :)

**Comment by Pseudonium** [comment]
Oh yes, that would be useful.

This came at pretty much the perfect time - I’ve finished writing the code for v1, and just need to do the documentation. I’ll make sure I include some examples.

To showcase formatting, I’ll probably just use a ‘Basic’ note type. My Anki default mode is dark, but I’ll put the light mode on for the examples.

**Comment by tallguyjenks** [comment]
I just tried images in neuracache and its not working very well and im already familiar with Anki and like how much you can throw at it. Ill definitely be giving this a try. need to carve some time out to set up and play but it is deff on my todolist now 👍🏻

**Comment by Pseudonium** [comment]
I've added two example pictures showing a bunch of markdown formatting, and also linked to a website that gives a markdown guide.

I think that should be enough, so I'll close this issue. Do let me know if there's other things you would find useful.

**Comment by tallguyjenks** [comment]
awesome! thanks!
