### ISSUE TITLE
Is there a way to edit the code to change the curly brace character?

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#101]
I intend to use  'CLOZE' syntax, i.e use the " ` " character to identify as cloze. It helps in making the notes readable without unnecessary curly brace. 
Can someone help me change the code to include this functionality?

**Comment by Pseudonium** [comment]
Problem with this is that this conflicts with the standard markdown `code` syntax.

**Comment by dummifiedme** [comment]
Yes, I knowthat is why I asked for an edit and not a permanent change for all. Since I almost never use the code blocks. And in Notion2Anki they use this to detect cloze which makes the notes look good in comparison to braces hanging around. I am even willing to use italics (`_abc_` or `*abc*`) too. Since they will look good while pubslihing notes, and I can have cards out as well. 

I wished to know where I can make the edit.. 
I had tried to edit code in another tool called Ankify and had managed to do so. This code is a bit heavy weight (and awesome!!). 

Just a request. If you do have time, please help me on this.

**Comment by Pseudonium** [comment]
Hmm, my idea would be to a regex substitution of everything surrounded by "`" to change it to be surrounded by "{" and then "}". Then, run the script normally, and then substitute back.

But I couldn't add this as a main feature in the script itself.

**Comment by dummifiedme** [comment]
Sure, I wouldn't want you to add it to the script. I wanted to know how to implement it?
:)
