### ISSUE TITLE
Folder based TARGET DECK and TAG

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#103]
Is it possible to include a folder based TARGET DECK option? 
It is possible to implement it using the current script but by making multiple instances of script and config and then sequentially or mannually running them via batch or something

I wondered whether we can insert configs for each folder which can contain the changes in settings or only those lines which needs to be altered in the main config file. This way we can just have a recursive run with different target decks or tags. Atleast for users with folder system (PARA based users)

**Comment by Pseudonium** [comment]
Yeah, I might add this in the future.

**Comment by rzfzr** [comment]
@Pseudonium the implementation for this could look like the following:
In the 'Defaults' section of the settings, 'Deck' and 'Tag' could accept a simple string as it is right now, or it could accept variables like what  obsidian-git plugin does for commit messages:
![image](https://github.com/user-attachments/assets/1ab6abc1-e8cc-43fc-861f-8119c93dd2a5)

**Comment by EngineerLeonJ** [comment]
do u get the solution?

> [@Pseudonium](https://github.com/Pseudonium) the implementation for this could look like the following: In the 'Defaults' section of the settings, 'Deck' and 'Tag' could accept a simple string as it is right now, or it could accept variables like what obsidian-git plugin does for commit messages: ![image](https://github.com/user-attachments/assets/1ab6abc1-e8cc-43fc-861f-8119c93dd2a5)
