### ISSUE TITLE
[Obsidian Plugin] Deck isn't created automatically when it doesn't exist

### ISSUE THREAD

**Issue by Raagaception** [Pseudonium/Obsidian_to_Anki#123]
I have been using the script for a few weeks now. If we specified a TARGET DECK in the Python script versions, it used to just create a deck if it didn't exist. In the Obsidian plugin, we get an error and cards aren't generated when the destination deck doesn't exist. Is this intended behavior? 

![image](https://user-images.githubusercontent.com/72780589/101970895-2d022700-3c53-11eb-84e0-b2ecd17635b4.png)
![image](https://user-images.githubusercontent.com/72780589/101970897-32f80800-3c53-11eb-8750-c0c2c2eb54ed.png)

**Comment by Pseudonium** [comment]
So it looks like this is expected behaviour - according to the AnkiConnect API, when you change the deck of an existing card, the deck gets created automatically. But if you try to add to a deck that doesn't exist, it throws an error.

**Comment by Raagaception** [comment]
I'm sure it was generated automatically for new cards in v2.2.2, albeit I like it better this way! Closing this issue, seeing that this feature is intended.
