### ISSUE TITLE
[Obsidian Plugin] Card IDs aren't generated when Default deck isn't specified

### ISSUE THREAD

**Issue by Raagaception** [Pseudonium/Obsidian_to_Anki#124]
Suppose we don't specify the default deck at all, I assumed it wouldn't generated the cards from notes which didn't have a target deck specified in them.
![image](https://user-images.githubusercontent.com/72780589/101971057-66876200-3c54-11eb-90dc-4b851142f1b1.png)

Instead, what happens is the cards without a target deck of course don't get generated; but the cards with a TARGET DECK in them get generated _without_ IDs. So if I keep running the script with these "wrong" settings, it keeps generating more and more cards without checking whether such a card already exists.

**Comment by Pseudonium** [comment]
Without IDs? And this happens on regular START END cards? Just wondering whether it might be a regex issue.

**Comment by Pseudonium** [comment]
Just tested this - let default deck be empty string, specified target deck, made a card. It got generated with an ID just fine.

**Comment by Raagaception** [comment]
It works at my end, too now. I don't remember the steps leading up to the error, hence closing the issue now. Will reopen if I remember how I did it.
