### ISSUE TITLE
[Obsidian Plugin] The ID line gets included in the flashcard itself

### ISSUE THREAD

**Issue by Raagaception** [Pseudonium/Obsidian_to_Anki#125]
Whenever we generate cards, we can still see the beginning format of the ID inside Anki flashcards themselves. Using the Obsidian Plugin version.
In Obsidian \:
![image](https://user-images.githubusercontent.com/72780589/101973082-6474d180-3c5b-11eb-94a7-2d7fd7e3e67f.png)
In Anki \:
![image](https://user-images.githubusercontent.com/72780589/101973087-6c347600-3c5b-11eb-9f30-bd7d6b6922c0.png)

**Comment by st3v3nmw** [comment]
A note to the dev, I fixed mine by reverting the ID_REGEXP_STR change made in [this commit](https://github.com/Pseudonium/Obsidian_to_Anki/commit/301be836ea0cee13862f2d88fbe0c78bcc3003b8).

**Comment by Pseudonium** [comment]
Oh wait, that's not how to fix it. I updated the regexps to get around this problem - check the wiki.

**Comment by st3v3nmw** [comment]
I'm not on the latest update, I think that's why.
Thanks.
