### ISSUE TITLE
[Obsidian Plugin] CORS error when trying to connect to AnkiConnect

### ISSUE THREAD

**Issue by martinsondergaard** [Pseudonium/Obsidian_to_Anki#128]
Although the standalone script works fine I am unable to get the plugin to work.
AnkiConnect is running correctly on 127.0.0.1:8765, but the plugin throws the following error:

```
Access to XMLHttpRequest at 'http://127.0.0.1:8765/' from origin 'app://obsidian.md' has been blocked by CORS policy: 
The 'Access-Control-Allow-Origin' header has a value 'http://localhost' that is not equal to the supplied origin.
```

It seems to think it might be a cross-site forgery attack.

**Comment by Pseudonium** [comment]
Oh yeah, check the new setup for how to fix this - essentially you add the obsidian origin to AnkiConnect's list of allowed origins

**Comment by martinsondergaard** [comment]
I guess I should have taken the time to read the setup page again :) 

Would be great for the user experience if you could use the plugin without having to manually change settings in AnkiConnect, but I imagine that isn't possible. 

Thanks for the fast response!
