### ISSUE TITLE
[Obsidian Plugin] Defaults Tag is ignored

### ISSUE THREAD

**Issue by martinsondergaard** [Pseudonium/Obsidian_to_Anki#129]
I have changed the defaults tag to `obsidian`, but the cards are still being tagged with the old tag `Obsidian_to_Anki` in Anki.

The only other setting I have changed is toggling CurlyCloze. Every other setting is default and the cards are otherwise added correctly.

**Comment by Pseudonium** [comment]
Oh, good catch! Can't believe I didn't spot this. Should be fixed for v3.2.0

**Comment by martinsondergaard** [comment]
Great!
