### ISSUE TITLE
Icon barely visible

### ISSUE THREAD

**Issue by archelpeg** [Pseudonium/Obsidian_to_Anki#133]
The icon is not easy to make out. Perhaps thicker lines and a transparent background would be better?
![grafik](https://user-images.githubusercontent.com/72164229/101988219-8c365a80-3c98-11eb-923c-2b0f7aeaa795.png)

**Comment by Pseudonium** [comment]
Ok, I'll see about improving this!

**Comment by Pseudonium** [comment]
Alright, I've made it so that the ribbon icon matches the underlying css for the built-in ribbon icons - before it was just a static black and white (so e.g. wouldn't change when you changed your css theme). Hopefully the new icon will look better!
