### ISSUE TITLE
Missing picture in Obsidian Readme

### ISSUE THREAD

**Issue by archelpeg** [Pseudonium/Obsidian_to_Anki#135]
The picture showing the config of AnkiConnect for The Obsidian Readme is not there.
Perhaps it would also be better to make it a codeblock and not a picture for easy copy‐pasting.

![grafik](https://user-images.githubusercontent.com/72164229/101992756-c530f800-3cb5-11eb-9b79-38255984bfc6.png)

**Comment by Pseudonium** [comment]
Good suggestion! Did this just now
