### ISSUE TITLE
Failed to update to 3.3.0

### ISSUE THREAD

**Issue by archelpeg** [Pseudonium/Obsidian_to_Anki#137]
Sorry for all the issues today, but updating to the newest version always throws a "failed to update".

I've tried restarting Obsidian, that didn't help.

**Comment by martinsondergaard** [comment]
Same problem. Unable to update. It seems Obsidian thinks there is a version 3.3, but 3.2 is the latest version on github.

**Comment by Pseudonium** [comment]
Oh yeah, that’s because I haven’t yet released the files for 3.3.0!

**Comment by archelpeg** [comment]
Ah, that makes sense.
