### ISSUE TITLE
Highlight is hard to be converted

### ISSUE THREAD

**Issue by iris2jane** [Pseudonium/Obsidian_to_Anki#138]
- **Compared to {cloze}, ==cloze== is harder to be converted.**

<img width="814" alt="image" src="https://user-images.githubusercontent.com/36763930/102010404-c7a85600-3d78-11eb-85b8-b8a7feb86b9b.png">

- **And it seems to be something wrong in 「highlight」**

![](https://user-images.githubusercontent.com/36763930/102009943-c590c800-3d75-11eb-9d86-73d2bd5cbb25.png)

**Comment by Pseudonium** [comment]
Fixed this for 3.3.1
