### ISSUE TITLE
Obsidian Plugin doesn't refreshes the card types

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#140]
If a particular card type is already set up with ReGex, it doesn't update if changed (added or deleted a field) in ANKI. The plugin fails to acknowledge that there has been some changes in the fields.

1. I tried refreshing the Obsidian. 
2. Tried resarting Obsidian.
3. Tried clearing Hash and Media (Those two options)

![image](https://user-images.githubusercontent.com/68785729/102021970-c04d7080-3da9-11eb-9d4b-659133b6eca9.png)
![image](https://user-images.githubusercontent.com/68785729/102021985-cd6a5f80-3da9-11eb-9622-cbe3084042d6.png)

EDIT:
Had to uninstall the plugin and try again to fix it.

**Comment by Pseudonium** [comment]
Yes, I just noticed this issue myself with some of my card types! Got a fix upcoming

**Comment by Pseudonium** [comment]
Should be fixed in v3.3.2
