### ISSUE TITLE
Context option

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#142]
The context option uses full path to the file, it crams up the ANKI space. Is it possible to have an option to use just the file name not the whole path?
Example:
For a file in folder `C://Users/Vault/A/B/C/Test.md`, I am getting this whole thing plus the added context (#s) which is really long.
Instead, if possible we could use the `basename` than the whole path.

Just a request. :)

**Comment by Pseudonium** [comment]
Right. As you can understand, I really want to avoid over complicating the settings too much. I’m going to refactor them in a future update (won’t remove any, just shuffle some around), will think about this then

**Comment by dummifiedme** [comment]
Sure.
I just thought that the ontext surely means to go up in the front of the card. And, providing the whole folder structure there (not even from the Vault Home but from the drive path!) isn't gonna help (anyone, I think). Plus, there is already an option to have file linked if thats what someone wants. Context should be rather clean in my opinion since its part of the front.

The Wiki here presents the context as `test.md > Title 1 > Subheading 1 > Subheading 2`,
which is exactly how it is supposed to be. 

But instead while execution, it gives `C://Users/dummifiedme/Vault/A/B/C/Test.md > Title 1 > Subheading 1 > Subheading 2`.

**Comment by Pseudonium** [comment]
The path should be given from the vault root - it shouldn't be an absolute path. Try something for me - in the Obsidian console, type `let x = await this.app.vault.getMarkdownFiles()`, and then type `x` (might be `undefined` for a short amount of time). Inspect the object and see what the `path` attribute on each file is - this is what the plugin adds as context.

**Comment by dummifiedme** [comment]
How to open the console?

**Comment by Pseudonium** [comment]
Ctrl-Shift-I or cmd-shift-i

**Comment by dummifiedme** [comment]
Oh, got it.
Its relative to Vault yes, my bad. 

My system is filled of cascading folders. So all my notes are deep inside folders. So it's just long even without absolute path :(  
I guess only thing that could work for cases like me is to have only the file `basename-uri` and the relative context.

I mean, it would be good to have just `test.md > Title 1 > Subheading 1 > Subheading 2` but I guess you or others might not be interested in it being like that ;) So its fine. Thanks anyway :)

**Comment by Pseudonium** [comment]
The main reason with me being a little hesitant about adding this is overcomplicating the settings. You probably remember when 'note substitutions' was a feature, and config files were enormous! I've learnt my lesson about this.

In a future update, I'm going to split the current settings into multiple tabs, which will hopefully be better for users. At that point, I'll probably be more open to requests like this. Will keep this issue open for now as a reminder!

**Comment by Pseudonium** [comment]
Ok, I didn't split the settings into multiple tabs - instead I put the note type table under a collapsible thing. I think that goes a long way to simplifying settings.

**Comment by dummifiedme** [comment]
The actual request is still open though. :)  
To have only the file name in the context instead of the whole path in the Vault

**Comment by Pseudonium** [comment]
I thought you said you were fine with it? I don't plan on changing this either.

**Comment by dummifiedme** [comment]
Oh. Alright. Its fine then. 🙂
