### ISSUE TITLE
Found a few bugs or stepdowns than the previous (script) versions

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#143]
While trying to use the plugin version for Obsidian, I came across BUGS or changes wrt to the original script:

1. Target Deck doesn't work if the Deck is not already created. Earlier it used to create the deck (SCRIPT mode). 
2. Same as Point 1 for the File Tags.
3. I don't see any IDs being created. Sometimes same card is added twice.
4. Remnote style messing with Target Deck lines if using cascading deck or tag names (::). Can be fixed to ignore those two lines, I hope?

PS. I am only pointing out what I found, no way complaining :) I am already indebted with the code. WOuld love to see if these things are fixed :)

**Comment by Pseudonium** [comment]
First of all, please do search to see if your issue has been cited already! This applies to 1 and 2. And try to keep issues related to one thing and one thing only.

3 - hopefully fixed in latest version (3.3.3), was experiencing same problem
4 - Interesting, I’ll see what I can do

**Comment by dummifiedme** [comment]
2 - Yes, It doesn't add it. I tried creating cards and it just gets one tag ie Obsidian_to_Anki. If I manually add a tag in ANKI and run the plugin again, it detects it and adds the tag.

**Comment by dummifiedme** [comment]
> First of all, please do search to see if your issue has been cited already! This applies to 1.

Well, I still couldn't find any issue linked with the deck. IF the deck mentioned in TARGET DECK line doesn't exist in ANKI, plugin won't create cards! or randomly creates some cards in default deck. That was my issue. I didn't see any such issue anywhere on the page nor any warnings or directions in the Wiki.

Please point me what should I do. I haven't been able to set up the thing smoothly.
Problems I am facing:

- random card generation, 
- duplicated cards upon re-run of the plugin, 
- no IDs after generation,
- many files are just ignored, 
- Target Deck not working if deck doesn't exist
- File Tags not working is tag doesn't exist.

**Comment by Pseudonium** [comment]
Issue number #123 .

Could you please refactor this into separate issues - it'll make my life much easier

**Comment by dummifiedme** [comment]
Sure
