### ISSUE TITLE
Header-paragraph style Regex generating cards randomly.

### ISSUE THREAD

**Issue by Raagaception** [Pseudonium/Obsidian_to_Anki#144]
The "header paragraph" style Regex broke after the last couple updates, for me. Now it seemingly generates cards at random. What could be the issue here?
![image](https://user-images.githubusercontent.com/72780589/102045531-552e8900-3dff-11eb-94aa-52e0bab5eee6.png)

My Regex line is:  `^#{6,}(.+)\n*((?:\n(?:^[^#].{0,2}$|^[^#].{3}(?<!<!--).*))+)` 
(it's supposed to create flashcards whenever the script sees 6 hashes)

**Comment by Raagaception** [comment]
Okay, it seems like the [Wiki ](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Header-paragraph-style) might be wrong in this instance. 

At the beginning, it reads 
![image](https://user-images.githubusercontent.com/72780589/102046003-60ce7f80-3e00-11eb-9daa-c146c6ab3dc1.png)
So, `^#{6,}(.+)\n*((?:\n(?:^[^#].{0,2}$|^[^#].{3}(?<!<!--).*))+)` didn't work for me.

But at the end, the script-only Regex line reads
![image](https://user-images.githubusercontent.com/72780589/102046021-704dc880-3e00-11eb-8a5e-9a21a7cb115c.png)
`^#{6,}(.+)\n+((?:[^\n#][\n]?)+)` works perfectly for me.

Could you please explain what's the difference between the two, and why doesn't the first one work for me?

**Comment by Pseudonium** [comment]
Try this regex instead - `^#{6,}(.+)\n*((?:\n(?:^[^\n#].{0,2}$|^[^\n#].{3}(?<!<!--).*))+)`

**Comment by Raagaception** [comment]
I have yet to stress-test it with my workflow, but it shows this warning instead of the usual success message with your new regex. Not anything to worry about I hope? (updating a couple cards here and there worked fine)

![image](https://user-images.githubusercontent.com/72780589/102083161-233a1880-3e39-11eb-8dff-15ce45cf5f98.png)

**Comment by Pseudonium** [comment]
Yeah maybe try deleting some of the cards you just added and the corresponding IDs, and re-running the script.

**Comment by Pseudonium** [comment]
I'll try to make sure these exceptions are displayed in a better way in an upcoming update

**Comment by Pseudonium** [comment]
Fixed in 3.3.4
