### ISSUE TITLE
Problem with MacOS Big Sur

### ISSUE THREAD

**Issue by danieltomasz** [Pseudonium/Obsidian_to_Anki#145]
I am getting following errors (Obdsian 0.9.20. OtA 3.3.3) 
```
Access to XMLHttpRequest at 'http://127.0.0.1:8765/' from origin 'app://obsidian.md' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://localhost' that is not equal to the supplied origin.
```

```
Failed to load resource: net::ERR_FAILED
```

**Comment by Pseudonium** [comment]
Check the setup instructions, you need to allow Obsidian to be a valid source for AnkiConnect requests

**Comment by danieltomasz** [comment]
Hi! Sorry I wasn't explicit,  I did modify the AnkiConnect config before posting here 
```
{
    "apiKey": null,
    "apiLogPath": null,
    "webBindAddress": "127.0.0.1",
    "webBindPort": 8765,
    "webCorsOrigin": "http://localhost",
    "webCorsOriginList": [
        "http://localhost",
        "app://obsidian.md"
    ]
}
```
https://github.com/Pseudonium/Obsidian_to_Anki/issues/128

**Comment by Pseudonium** [comment]
Oh, interesting! You might need to restart Anki then? These sorts of things sometimes require a restart.

If that fixes it, I'll add that as a step to the setup

**Comment by danieltomasz** [comment]
Yes, it works! I tried to restart both anki and obsidian before but only now it worked

**Comment by Pseudonium** [comment]
Nice! I've added this as a step to the setup.
