### ISSUE TITLE
Request to fit this anki template

### ISSUE THREAD

**Issue by iris2jane** [Pseudonium/Obsidian_to_Anki#146]
[Mix.apkg.zip](https://github.com/Pseudonium/Obsidian_to_Anki/files/5688449/Mix.apkg.zip)
This is a fairly powerful anki template for mixed `Q&A` and `Clozing`, but when I use this template, the plug-in cannot convert `==cloze==` and `{cloze}` into `{{C1: cloze}` in anki.

👇This is the normal template looks like

![iShot2020-12-14 19 20 17](https://user-images.githubusercontent.com/36763930/102075658-862fad80-3e41-11eb-9d18-094785d0e61e.gif)

**Comment by Pseudonium** [comment]
If you just change the template name to include ‘Cloze’, it should work. The plugin won’t always convert curly braces to cloze deletions - for example, they are used often in math!

**Comment by iris2jane** [comment]
Thank you~It really works!
