### ISSUE TITLE
IDs are not generated.

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#148]
Since there is no ID generation in the md files the following duplicated cards are generated upon re-run of the plugin.

**Comment by dummifiedme** [comment]
Probably due to the script stopping mid way.
https://github.com/Pseudonium/Obsidian_to_Anki/issues/147#issue-766322102

**Comment by dummifiedme** [comment]
EDIT: it was related to the mentioned issue, but please take note. :)

**Comment by Pseudonium** [comment]
What version of the script are you running?

**Comment by dummifiedme** [comment]
Version 3.3.3, the Latest One.

**Comment by Pseudonium** [comment]
Fixed in 3.3.4

**Comment by dummifiedme** [comment]
What fix you have there?
Basically, any error caused the script to stop and not process IDs or tags.

**Comment by Pseudonium** [comment]
Yes, I read and understood the issue. The script will now catch the error and log it to the console, instead of stopping execution. Which means that successfully added cards get their IDs written.

**Comment by dummifiedme** [comment]
That's great 👍
