### ISSUE TITLE
Not all files are scanned

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#149]
Not all the files in the vault are being scanned into ANKI, each run is randomlly creating cards from one file or the other and sometimes some cards are ignored.

**Comment by dummifiedme** [comment]
This is probably due to script stopping mid way.
https://github.com/Pseudonium/Obsidian_to_Anki/issues/147#issue-766322102

**Comment by Pseudonium** [comment]
Fixed in 3.3.4
