### ISSUE TITLE
Impossible to make templates for Anki notes due to error

### ISSUE THREAD

**Issue by martinsondergaard** [Pseudonium/Obsidian_to_Anki#150]
I was having the same problem as  #148 (and also related to #147 and #149)  where the cards were created but no id was added to the obsidian note. 
I realized it was because I had made some Anki note templates without any content  and the script was throwing an error before it could add the final id's; `Uncaught (in promise) cannot create note because it is empty`.

The ability to make templates for Anki notes is kind of crucial. It is too cumbersome to add hundreds or even thousands of notes if you manually have to write the whole Anki note syntax. Either the plugin should disregard completely empty notes or, even better, there should be a setting to specify a template folder which would be skipped when scanning files for Anki notes.

**Comment by Pseudonium** [comment]
This will be fixed in a future update where I refactor error handling. I'm guessing there aren't any custom regexps that suit your note types?

**Comment by martinsondergaard** [comment]
Not sure how a custom regexp would fix this issue.

**Comment by Pseudonium** [comment]
Well, they're often more convenient to use than the START END syntax. E.g. all my notes use custom regexps. And then I don't have to use templates.

**Comment by Pseudonium** [comment]
In any case, this will be fixed next release with the introduction of proper error handling.

**Comment by Pseudonium** [comment]
Fixed in 3.3.4
