### ISSUE TITLE
enhancement: the obsidian tags could directly be inserted into notes?

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#151]
Can there be implementations of using obsidian tags in and around the extent of a note captured be included as ANKI card tag (excluding the #)? That way we can have a seamless linking with the note without having to worry about tagging the same notes twice separately.
It could work like charm for regexp users.

**Comment by Pseudonium** [comment]
The only way I could see this working is using the tags of the file in the frontmatter or something. Not sure exactly what your request is meant to be? Could you provide an example?

**Comment by dummifiedme** [comment]
For example, this is a regex based note:

---

This is a question #flashcard 
This is the Answer.

---
Here the first line is rightly captured as question field and the second line is answer field.

So if my note is like below, we can have something that identifies the tags in the note.

---

This is a question #flashcard #tag3
This is the Answer. #tag1 #tag2

---

So the ANKI card gets tags as: tag1, tag2 and if possible tag3 as well.

All in all, if the script can identify all the #tags in the note as anki tags, that would be great. I know it might not be possible, just wanted to share if its possible?

The tags after #flashcard is possible as far as I know from a different plugin in Obsidian does that (Flashcards Plugin). See the local tag here: https://github.com/reuseman/flashcards-obsidian/wiki#tags

**Comment by Pseudonium** [comment]
You can already do this by adding a Tags: line to your note

**Comment by dummifiedme** [comment]
You mean even in thr Regex?

**Comment by Pseudonium** [comment]
Yes - this is detailed in the wiki on the regex page, subsection ‘Tag Formatting’.

**Comment by Pseudonium** [comment]
I see your point about the #tags being more convenient, though I worry that not all users would want this functionality. And it could be a setting, but you’ll have to agree the current settings are already quite complicated!

**Comment by dummifiedme** [comment]
Haha, Yes. I agree. 
I am just looking forward to clean the notes as far as possible as you might have noticed. I believe your motivation is the same ;)

Only difference I think is that you tend to have small notes, while my notes, sometimes, are quite large (study notes). I manage to include different styles of cards via making different card types in ANKI while slight changes in the Regex you provided :)  

I would have been interested in learning to code these things as well, but right now I have to prepare for a really big exam which requires a lot of time. I hope I can contribute in future.

**Comment by Pseudonium** [comment]
Yeah, the design philosophy is for atomic notes rather than huge notes, though I do sometimes have large notes! Of course, that hasn't stopped me from adding thousands of cards to Anki.

**Comment by Pseudonium** [comment]
Right, so this would actually be fairly easy to implement. Just need to add a setting to toggle this on or off (by default off). Behaviour will be that it scans all fields for tags of the form #tag, and adds that to the note in Anki.

By the way, doing #flashcard #tag3 as per your example wouldn't work with neuracache regex, since that requires #flashcard to be at the end of the line. But doing #tag3 #flashcard would work fine

**Comment by Pseudonium** [comment]
Yep, implemented this as a feature in current development branch!

**Comment by dummifiedme** [comment]
That's cool.
Now I have a query, will that tag be added to all the notes in the file or just the note that contains those tags?

**Comment by Pseudonium** [comment]
Yeah only on the second note. The parsing engine will only read tags from the fields of the current note.

**Comment by dummifiedme** [comment]
Amazing!
