### ISSUE TITLE
Accessing Obsidian's console

### ISSUE THREAD

**Issue by uuuser-name** [Pseudonium/Obsidian_to_Anki#152]
While scanning the vault with the Obsidian plugin, a message shows "Scanning vault, check console for details". 
How can one access the mentioned console?

**Comment by Pseudonium** [comment]
Ctrl-Shift-I or Cmd-Shift-I. Hmm, do you think that it would be worth adding this to the notice message? It's not something the plugin makes, it's inbuilt to Obsidian.

**Comment by Pseudonium** [comment]
The trouble with putting all the logs into notices (the popups you see) is that they go by very quickly, and you can't access a 'history' of displayed notices.

**Comment by uuuser-name** [comment]
Thanks.
I think it may be worth it to write how to access the console, maybe in the plugin's description, or in the wiki.

**Comment by Pseudonium** [comment]
Yep, I'll put it in the Troubleshooting section. Thanks for this, we've improved the experience for future users!
