### ISSUE TITLE
Bug: incorrect code block escaping

### ISSUE THREAD

**Issue by mnowotnik** [Pseudonium/Obsidian_to_Anki#154]
Code blocks get rendered with html escape codes:

```python
l.append(&#x27;foo&#x27;)
```

If I change line 469 in file obsidian_to_anki.py from
`                html.escape(code_match)`
to
`                code_match`

the code block gets rendered as:

`l.append('foo')`.

**Comment by Pseudonium** [comment]
I see. I encountered this issue with `<` and `>` signs initially with math matches, hence why I added the HTML escape. You're saying that they're not needed for code blocks then?

**Comment by Pseudonium** [comment]
Yep, I've just tested this, and got exactly the behaviour you described! I didn't realise it'd be different for math versus code... I'll fix this for next update (both in obsidian plugin and python script)

**Comment by mnowotnik** [comment]
Obsidian plugin works fine. Just checked it. You're right that symbols `<` and `>` need to be escaped. Here is a sample of properly rendered output of obsidian plugin:

```<link href="https://cdn.jsdelivr.net/npm/highlightjs-themes@1.0.0/arta.css" rel="stylesheet"><p>papa</p>
<pre>
<code class="hljs python language-python">
<span class="hljs-number">1</span> &lt; <span class="hljs-number">2</span>
<span class="hljs-number">3</span> &gt; <span class="hljs-number">3</span>
print(<span class="hljs-string">'foo'</span>)
print(<span class="hljs-string">"foo"</span>)
</code></pre>
<pre> H l 
   l l 
</pre>
<pre><pre><code class="hljs python language-python">print(<span class="hljs-string">'foo'</span>)
print(<span class="hljs-string">"foo"</span>)
</code></pre>
</pre>
```

**Comment by mnowotnik** [comment]
Actually, python part escapes code twice. Once, first time manually via `html.escape`, second time using `md_parser` (or so I think).

Btw, thanks for awesome work
