### ISSUE TITLE
Bug & Feature Request -- Ignore particular folder in order to ignore templates

### ISSUE THREAD

**Issue by tallguyjenks** [Pseudonium/Obsidian_to_Anki#160]
i see the functionality for specifying where to send cards based on folders

"if in folder `Mathmatics/` then go to the deck `Mathmatics`"

but i use the Obsidian templates a lot to insert the syntax for the Anki cards and the templates are getting picked up as intended cards when the plugin scans my vault

of is there an intended approach around this that I'm missing?

**Comment by Pseudonium** [comment]
If your templates are blank, then it won’t actually add a card (just log a warning). If it isn’t blank, you could e.g. send it to a ‘templates’ deck or something?

**Comment by tallguyjenks** [comment]
For the inline cards templates, I use space holders for easy double click and replace writing

`STARTI [Basic] Front: <++> Back: <++> Tags: <++> ENDI`

but this is the whole template. i'd prefer to not have to delete `TARGET DECK: Template`
out of every inline card template insertion I perform just to keep the template file from pushing to Anki:

```md
TARGET DECK: Template
STARTI [Basic] Front: <++> Back: <++> Tags: <++> ENDI
```

**Comment by Pseudonium** [comment]
Oh wait, so you're already pushing it to a templates deck? Is the issue that you're getting identifiers added to your templates then? In that case, what you can do is let the script add the template, remove the identifier, and then you'll be set. It won't add duplicate cards.

**Comment by tallguyjenks** [comment]
> so you're already pushing it to a templates deck?

No, Currently i am wanting all my templates in `/Templates/Anki/*` to be completed ignored and i'd prefer to not have a template deck at all

> what you can do is let the script add the template, remove the identifier, and then you'll be set. It won't add duplicate cards.

I'll do this as a work around but my ideal outcome is the ability to choose a directory to be ignored by the vault-wide scan

**Comment by Pseudonium** [comment]
Yeah, I might be able to add that in a future update. Sounds like a good feature!

**Comment by tallguyjenks** [comment]
Woo hoo! 🙌🏻

**Comment by corode** [comment]
@Pseudonium @tallguyjenks This might be a little simplistic and maybe completely wrong (I haven't had a chance to go through the code properly), but could we add an 


```python
def recursive_directory_function(dirpath):
    if dirpath != config['path_to_directory_to_ignore']:
        recusive_directory_function(dirpath)

```

to do this?

**Comment by Pseudonium** [comment]
@corode Ah, thanks for your suggestion! I had another idea in mind.

Namely, I already have a function in `files-manager.ts`, called `getFolderPathList`, that returns for a given the file the list of folders it's contained in, from deepest outwards. E.g. if the path to the file was `Folder1/Folder2/Folder3/test.md`, it would return the list `[Folder1/Folder2/Folder3, Folder1/Folder2, Folder1]`.

Then, what I can do is check if any of these folders matches a user-specified template folder name, and if so ignore it. This means both the template folder and any file in its subfolders are ignored automatically!
