### ISSUE TITLE
Nothing is exported - language issue in the settings?

### ISSUE THREAD

**Issue by gala8y** [Pseudonium/Obsidian_to_Anki#161]
I installed Anki first using Polish language for UI and I get settings in Obsidian_to_Anki in Polish - specifically Note Type table contains Polish terms - see image below:

![screenshot 2020-12-15 (10)](https://user-images.githubusercontent.com/1263605/102235714-ea5e7a00-3ef2-11eb-9cf5-e191d1068707.jpg)

I already tried changing UI language in Anki to English, as well as reinstalling it.

I created 2 cards in one Obsidian note as follows:

START
Podstawowy
Przód: This is a test.
Tył: Test successful!
Tags: Testing
END

START
Basic
Front: This is a test 2.
Back: Test successful really!
Tags: Testing2
END

Nothing gets exported. I would appreciate any help making it run.
I am on Win10.

**Comment by Pseudonium** [comment]
Hmm, could you show what the console says? Open it with ctrl-shift-i

**Comment by gala8y** [comment]
> 
> 
> Hmm, could you show what the console says? Open it with ctrl-shift-i

Like hitting ctrl-shift-i in main Obsidian window? What part do you need?

**Comment by Pseudonium** [comment]
If you could take a screenshot of what the console looks like after a failed scan, that would be useful. Here's what the console looks like for reference - 
![image](https://user-images.githubusercontent.com/27702145/102238881-2cd18800-3eee-11eb-97cd-b9fc95f8f3f3.png)

**Comment by Pseudonium** [comment]
Ah yes, you're probably right in that it might be a language issue. Did you try regenerating the note type table?

**Comment by gala8y** [comment]
> 
> 
> Ah yes, you're probably right in that it might be a language issue. Did you try regenerating the note type table?

I found this command and tried it.

**Comment by Pseudonium** [comment]
No problem - I'll see about making the error clearer in a future update. Thanks for reporting this!

**Comment by gala8y** [comment]
Thanks again @Pseudonium for your quick replies.

For eternity... after I uninstalled Anki from the computer, I had to manually delete folders with left over files:
`C:\Users\USER\AppData\Roaming\Anki2`
`C:\Users\USER\AppData\Local\Anki`
After reboot I reinstalled Anki and Obsidian_to_Anki and... it works!

**Comment by Pseudonium** [comment]
Nice! I’ll still keep this issue open to remind me to add proper error handling for this - something like “Warning! Note type [insert note type] not recognised”

**Comment by Pseudonium** [comment]
Yep, have added error handling for this in my latest commit. It'll also log the file in which the unrecognised note type was identified. Expect to see this soon!

**Comment by Pseudonium** [comment]
Fixed in 3.4.1
