### ISSUE TITLE
Cannot scan

### ISSUE THREAD

**Issue by iris2jane** [Pseudonium/Obsidian_to_Anki#162]
The plugin can only scan several new documents at a time. If there are too many documents, it scans nothing.

**Comment by Pseudonium** [comment]
Hmm, I haven't experienced this behaviour - I've successfully scanned hundreds of files at a time after clearing the file hash cache. What does the console look like after a failed scan? Open it with ctrl-shift-i or cmd-shift-i - for reference, here's what it looks like normally 
![image](https://user-images.githubusercontent.com/27702145/102239091-6609f800-3eee-11eb-9e54-3880dabc2b23.png)

**Comment by iris2jane** [comment]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/36763930/102240543-f23e0e80-3f32-11eb-8587-3ff6a6591de3.png">

**Comment by Pseudonium** [comment]
This seems related to #159 , I suspect the script is not able to find that referenced media file.

Try typing this in the console, substituting `file_path` for a string of the path to the file - `this.app.metadataCache.getFirstLinkpathDest("iShot2020-09-16 09.37.23.jpg", file_path)`

**Comment by iris2jane** [comment]
Yeah, the scan failure may be due to some nonexistent links.  Can these errors be prompted or skipped？

**Comment by Pseudonium** [comment]
Yeah I'll add this to the error-handling in a future update

**Comment by iris2jane** [comment]
Thanks for your patience~

**Comment by Pseudonium** [comment]
Yep, I fixed this in a recent commit. Expect this next release!

**Comment by Pseudonium** [comment]
Fixed in 3.4.1
