### ISSUE TITLE
Context not appearing on cards

### ISSUE THREAD

**Issue by corode** [Pseudonium/Obsidian_to_Anki#169]
I assume that the 'Add Context' option adds a breadcrumbs trail within the anki card field itself? If so then the context does not appear. I thought at first it might be because I created the files without the headings but then I deleted and remade the cards and the context still didn't appear. Maybe I am doing something wrong?

For reference, here is the markdown I am using:

```
# Benzene

## Structure

Why were models of Benzene that appeared like this initially rejected?
![[Pasted image 20201216170624.png]]

---
- Benzene failed to give any of the reactions of alkenes.
- It also appeared to be much more stable (lower in energy) than typical alkenes.
<!--ID: 1608139621099-->


Kekule's structure

---
![[Pasted image 20201216171007.png]]
<!--ID: 1608139734727-->
```

**Comment by Pseudonium** [comment]
Hmm, I just tested this with 'Add Context' on and it worked fine? Does the console show any errors (open with ctrl-shift-i or cmd-shift-i)? Also, you might need to slightly change the file - changed settings only apply to new or changed files for efficiency. Often what I do is just keyboard mash somewhere where cards don't get affected, run the script, and then delete my mashed characters.

You could also clear the file hash cache for this, but that means re-scanning the entire vault, which you might not want!

**Comment by corode** [comment]
I tried all those things and it did not work. But then I updated and now it works perfectly. 

P.S. Context has me completely sold on Obs to anki, It's amazing!
