### ISSUE TITLE
Failed to install plugin "Obsidian_to_Anki"

### ISSUE THREAD

**Issue by ManHunted** [Pseudonium/Obsidian_to_Anki#171]
Hello!
I am a premed student hoping to use Obsidian as my primary study/knowledge management tool. When I stumbled upon your obsidian_to_anki script I thought it was a fantastic idea, but I have no python or coding knowledge and ran into some issues setting up the python script. Now that there is a plugin (thank you!) I tried setting it up again and ran into another problem, see below. 

![image](https://user-images.githubusercontent.com/76140609/102437555-51a62800-3fe0-11eb-9584-ec735a08579d.png)

Any ideas on what went wrong? 

Thanks for the help!

**Comment by Chris8031** [comment]
I came here to say the same thing. I too am having trouble installing the plugin and don't have any python/coding knowledge either. 
![Uploading fail.JPG…]()

**Comment by Pseudonium** [comment]
Oh, sorry! For some reason GitHub saved it as a draft instead of publishing it

**Comment by Pseudonium** [comment]
Should be fixed now
