### ISSUE TITLE
what's the difference between flashcard and this plugin?

### ISSUE THREAD

**Issue by Jackiexiao** [Pseudonium/Obsidian_to_Anki#175]
I try flashcard plugin(which is pretty simple, I just need to use tag **#card**), and also want to try obsidian-to-anki, but at first view, obsidian-to-anki seems a little complex, for example 
```
START
Basic
This is a test.
Back: Test successful!
Tags: Testing
END
```
in flashcards
```
# this is a test #card  
Test successful!
```
is there a simple way to add card like flashcards?

**Comment by Pseudonium** [comment]
Check out the custom regexps

**Comment by dummifiedme** [comment]
> I try flashcard plugin(which is pretty simple, I just need to use tag **#card**), and also want to try obsidian-to-anki, but at first view, obsidian-to-anki seems a little complex, for example 
> ```
> START
> Basic
> This is a test.
> Back: Test successful!
> Tags: Testing
> END
> ```
> in flashcards
> ```
> # this is a test #card  
> Test successful!
> ```
> is there a simple way to add card like flashcards?

Flashcards Plugin is a very basic subset of this Plugin. Obsidian to Anki provides a flexible way to make cards, you can have any pattern to pick the cards, while flashcard app restricts you to a particular style.

As @pseudonym suggested, check out the regex types

**Comment by Jackiexiao** [comment]
thx! I will try when I have time

**Comment by Jackiexiao** [comment]
if I want use both RemNote single-line style and Question answer style for basic card, what should I do ? @Pseudonium

**Comment by dummifiedme** [comment]
I know you have asked the developer, but I can answer that so here it is.

Just make two card clone card types in ANKI and assign two different regex.

**Comment by Jackiexiao** [comment]
thx!
