### ISSUE TITLE
No cloze found on card

### ISSUE THREAD

**Issue by DutchPete** [Pseudonium/Obsidian_to_Anki#178]
I am a bit confused. I got this pop-up:
![image](https://user-images.githubusercontent.com/10794265/103072456-49e11780-45ce-11eb-9cb5-2da1a46c3912.png)

So, I clicked on Edit to see which card it is, then went to that note in Obsidian, deleted the block that served to make the card. The deleting was done by creating a new block:

DELETE
ID: the number as shown in the original note

Then, in the settings I clicked on the 2 cache clear buttons, and created a new cloze with the same text as the deleted one. But I got that "no cloze found" message again. 4 of my 6 cloze cards are like that.

**Comment by Pseudonium** [comment]
Hmm, that’s odd. What do the cloze cards look like in your document?

**Comment by DutchPete** [comment]
![image](https://user-images.githubusercontent.com/10794265/103269078-ac1a8d80-49bd-11eb-9b9c-47db47ef78b1.png)

**Comment by DutchPete** [comment]
Any ideas?

**Comment by DutchPete** [comment]
Any news?

**Comment by problemadder** [comment]
maybe try regex for cloze deletion. 
maybe your anki cloze deletion template is broken.
you could test it with another fresh anki profil to be sure about it.
seems not to be a problem in general

**Comment by DutchPete** [comment]
I went through quite an extensive trial and error session with you when it was still only a script, before it was a plug-in. Now you suggest another trial and error way to fix it. Sorry, I am not prepared to spend more time doing this. I will uninstall the plug-in.

**Comment by problemadder** [comment]
Oh that's a pity. It's such a great tool for learning. Sad to hear that you
give up. Have a nice day

**Comment by DutchPete** [comment]
Anki is a great tool for learning indeed, and I did not say I am giving up Anki. I am giving up your plug-in. Sorry, but I am not prepared to invest more trial and error time into fixing your plug-in. Nothing personal, just a question of priorities.

**Comment by stefanpricopie** [comment]
Have you tried changing it with {{c1::adversity}}? I had this issue once and this solved it

**Comment by DutchPete** [comment]
@stefanpricopie thanks for your reply.

I stopped using Anki and consequently the Obsidian plug-in too.
