### ISSUE TITLE
Plugin Not performing scans at all -- console error message

### ISSUE THREAD

**Issue by tallguyjenks** [Pseudonium/Obsidian_to_Anki#186]
Obsidian v0.10.5
Plugin latest version
refreshed with `ctrl-r`
created a minimal reproducible example of a Basic card going to a brand new deck. and this is what i get every scan:

![image](https://user-images.githubusercontent.com/29872822/103491464-f09c9380-4dd8-11eb-9131-811a267addbc.png)

I've changed nothing since my last successful scan with the plugin

my minimal reproducible example:

![image](https://user-images.githubusercontent.com/29872822/103491543-8cc69a80-4dd9-11eb-881a-99f8a04eb603.png)

![image](https://user-images.githubusercontent.com/29872822/103491497-32c5d500-4dd9-11eb-9dc1-3040e837a0f8.png)

**Comment by tallguyjenks** [comment]
Resolved. apparently having inline card starters `STARTI` and `ENDI` even wrapped in back ticks didn't prevent them from being picked up and causing problems.

**Comment by Tinuvia** [comment]
Thank you for posting the issue and your solution - they helped me solve my issues too!
