### ISSUE TITLE
Bug: update regex don't work

### ISSUE THREAD

**Issue by Jackiexiao** [Pseudonium/Obsidian_to_Anki#193]
I simply change Question Answer Style 
```
^Q: ((?:.+\n)*)\n*A: (.+(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)
```
to 
```
^F: ((?:.+\n)*)\n*Y: (.+(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)
```

but I try again, it won't add my card 
```
F: question
Y: answer
```

I want to add a new custom regex for #192  , I use regex below, but it doesn't work
```
^\- ((?:.+\n)*)\n*\t\- (.+(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)
```

**Comment by Jackiexiao** [comment]
btw, I can't find Regex option in obsidian_to_anki setting 
 `Ensure that the 'Regex' option is checked` (which is from https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Question-answer-style#obsidian-plugin-users )
![Uploading image.png…]()

**Comment by Jackiexiao** [comment]
ok...f**k, I just realize when I paste regex in obsidian, it will turn into `^Q: ((?:.+\\n)\*)\\n\*A: (.+(?:\\n(?:^.{1,3}$|^.{4}(?<!<!--).\*))\*)` ... But it good for me to learn `obsidian_to_anki.py`

**Comment by AlexAndHisScripts** [comment]
I can't find the tick-regex either.

**Comment by timblaktu** [comment]
Me neither, is the documentation outdated/wrong? My understanding is that you don't need the `START`/`END` bookends when using regex. Can someone confirm?
