### ISSUE TITLE
Tags do not get into Anki when using QA-style regex

### ISSUE THREAD

**Issue by borisnaydis** [Pseudonium/Obsidian_to_Anki#196]
I've tried to specify tags in all ways I could imagine, but they still don't get into the DB.
I'm using the custom regex from [this](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Question-answer-style) wiki-page.
But the standard block style and [markdown table style](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Markdown-table-style) work fine.

Maybe I'm missing something. Could you advise me on what to do next?

```markdown
#tag1
Q: question2 #tag2
A: answer2 #tag3
<!--ID: 1610066316321-->


Tags: tag21 tag22

---
```

![image](https://user-images.githubusercontent.com/24412929/103960453-3e135a80-5163-11eb-8175-54e85cf37b48.png)

**Comment by fgsummer** [comment]
May I also add, that I do not get   for Q: A: Style questions. 
This is may regex (the same as refered above)
^Q: ((?:.+\n)*)\n*A: (.+(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)

**Comment by problemadder** [comment]
this should work:

Q: question2 
A: answer2 Tags: tag2, tag3
<img width="319" alt="Screenshot 2021-01-18 at 22 55 52" src="https://user-images.githubusercontent.com/49922107/104966072-58a9c700-59e0-11eb-844b-ee8ee7041192.png">

**Comment by borisnaydis** [comment]
Thanks, @problemadder for the suggestion. This indeed works, but I hoped there is something that looks a bit better.

**Comment by NewEpoch2020** [comment]
> Thanks, @problemadder for the suggestion. This indeed works, but I hoped there is something that looks a bit better.

I used a **single closed** HTML tag to add TAGS, which might look a little better.
```
Q: question2
A: answer2 
<meta> Tags: tag2, tag3 
```
