### ISSUE TITLE
Exalidraw support in Obsidian Plugin

### ISSUE THREAD

**Issue by Raagaception** [Pseudonium/Obsidian_to_Anki#243]
There is a nifty new plugin which was released recently, the [Obsidian Excalidraw plugin](https://github.com/zsviczian/obsidian-excalidraw-plugin). It allows us to create and embed Excalidraw files, draw and edit them within Obsidian itself. 

Is there any chance that the Excalidraw embeds could work in conjunction with the Anki exports? A system which converts the Excalidraw into a normal image file and puts it in an Anki would have infinite possibilities. 

This is how an Excalidraw plugin embed looks like inside Obsidian :
- edit mode : <br>![](https://i.imgur.com/eTDwdPZ.png)
- preview : <br>![](https://i.imgur.com/CTw6GCx.png)

Please do look into it whenever you've got the time, and thanks for the effort you put into this wonderful plugin!

**Comment by Raagaception** [comment]
The plugin now automatically creates a .png which is a carbon-copy of the .excalidraw file, so this feature request won't be required. Closing.

**Comment by adamcole123** [comment]
I'm not seeing the diagram in my anki cards when I use excalidraw, it just shows the obsidian link:

![Screenshot_20230423-140057~2.png](https://user-images.githubusercontent.com/32772788/233841319-4a9db073-eb19-40e2-ad43-ff84f879168b.png)

![Screenshot_20230423-140031~2.png](https://user-images.githubusercontent.com/32772788/233841326-ab030aa4-09b8-436d-9239-181313847f04.png)
