### ISSUE TITLE
Flashcard creation inside of Codeblocks

### ISSUE THREAD

**Issue by TobiasKlosek** [Pseudonium/Obsidian_to_Anki#245]
Hey, 

I would love to create Flashcards inside these admonition-plugin [Admonition-Plugin](https://github.com/valentine195/obsidian-admonition) but Obsidian_to_Anki is ignoring these Codeblocks somehow..

![image](https://user-images.githubusercontent.com/61796661/116404520-feb26c00-a82e-11eb-8394-08ba0b424baa.png)

Im using Neuracache Style.. this would be my modified regexp `title: ((?:[^\n][\n]?)+) #flashcard ?\n*((?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))+)` starting at the begin of title and ending with an obsidian-comment.

**Comment by TobiasKlosek** [comment]
I have found a solution by myself. Changes in `main.js`:

![image](https://user-images.githubusercontent.com/61796661/116426157-27446100-a843-11eb-98da-bd5116f284a8.png)

**Comment by TobiasKlosek** [comment]
Hm.. seems that the image-transfer is broken.. 

![image](https://user-images.githubusercontent.com/61796661/116431897-7c36a600-a848-11eb-938a-8d772c8058a9.png)

![image](https://user-images.githubusercontent.com/61796661/116431925-80fb5a00-a848-11eb-811b-1e49b3921999.png)

![image](https://user-images.githubusercontent.com/61796661/116431943-85c00e00-a848-11eb-993e-e094d2e330bf.png)

**Comment by TobiasKlosek** [comment]
The Problem is on Obsidian's site, there `file_cache` dont expect attachements located inside codeblocks.. i have rewritten the `getAndFormatMedias()` to determine the values needed to copy relevant path and filenames.

**Comment by Husky22** [comment]
Hi,
I am interested in your solution to this problem but can't find OBS_DISPLAY_CODE_REGEXP.
Would you be so kind and tell me what exactly you did to solve this problem?

**Comment by TobiasKlosek** [comment]
@Husky22 hey, sorry for the late answer. The variable should be in the `main.js`. Here is the edited part:
```javascript
const OBS_INLINE_MATH_REGEXP = /(?<!\$)\$((?=[\S])(?=[^$])[\s\S]*?\S)\$/g;
const OBS_DISPLAY_MATH_REGEXP = /\$\$([\s\S]*?)\$\$/g;
//const OBS_CODE_REGEXP = /(?<!`)`(?=[^`])[\s\S]*?`/g;
const OBS_CODE_REGEXP =/&[\s\S]*?&/g;
// const OBS_DISPLAY_CODE_REGEXP = /```[\s\S]*?```/g; Filtered every Flashcard within Codeblocks
const OBS_DISPLAY_CODE_REGEXP = /§[\s\S]*?§/g; // Since no Flashcard are created within these characters, everything should be fine
```

**Comment by malmius** [comment]
Hi,
I've tried to get images to work in admonitions for Anki cards as well, but it didn't work (I couldn't figure out how to extract the correct embed-data...). I'd be really grateful if you could provide the code for changing the `getAndFormatMedias()` method...

**Comment by TobiasKlosek** [comment]
@malmius sure, here you go.. a little bit dirty solution but it works nicely :)
```javascript
    getAndFormatMedias(note_text) {
      if (!(note_text.includes(".png"))) {
        console.log("Keine Bilder gefunden");
        return note_text;
      }
      console.log(note_text)
      var matches = note_text.match(/\!\[\[(.*)\]\]/g);
      //console.log(matches)
      matches.forEach(match => {
        var original = match;
        var link = original.substring(3,original.length-2);
        var displayText = link;
        if (note_text.includes(original)) {
          this.detectedMedia.add(link);
          if (AUDIO_EXTS.includes(path.extname(link))) {
              note_text = note_text.replace(new RegExp(escapeRegex(original), "g"), "[sound:" + path.basename(link) + "]");
            }
          else if (IMAGE_EXTS.includes(path.extname(link))) {
              note_text = note_text.replace(new RegExp(escapeRegex(original), "g"), '<img src="' + path.basename(link) + '" alt="' + displayText + '">');
              //console.log("Bild enthalten?", IMAGE_EXTS.includes(path.extname(link))); // DEBUG If Note contains img
              console.log("Note-Text", note_text); // DEBUG If Note contains img
            }
          else {
              console.warn("Unsupported extension: ", path.extname(link));
          }
        }
      });
      
      return note_text;
    }
```
