### ISSUE TITLE
Clozes in parts of a list create codeblocks when rendering markdown

### ISSUE THREAD

**Issue by niposch** [Pseudonium/Obsidian_to_Anki#250]
I want to create an anki card looking like this:
![image](https://user-images.githubusercontent.com/45246069/118407603-c5c52480-b681-11eb-8d9d-40cc0e9eb461.png)

I use double equal signs as ==clozes==.
From a list looking like this:
![image](https://user-images.githubusercontent.com/45246069/118407142-9e6d5800-b67f-11eb-8b4c-2a8fe141840f.png)

which renders to:
![image](https://user-images.githubusercontent.com/45246069/118407105-65cd7e80-b67f-11eb-9dc9-037c178591f8.png)
 

But when I parse the vault with the Obsidian_to_Anki Obsidian Extension, it turns into:
![image](https://user-images.githubusercontent.com/45246069/118407213-fa37e100-b67f-11eb-92a6-b20d8c01d222.png)
![image](https://user-images.githubusercontent.com/45246069/118407959-85ff3c80-b683-11eb-8e8c-d5529bc9a2e1.png)
The list partly turns into a code block and does not properly render.  (the Anki cards are still added properly)

I have an idea how to alleviate this problem with an opt-in feature (opt in via the settings of obsidian).

Adding the option to move ID: to the end of the cloze text block (without adding a new line in front of it) (Enabled on a per-regex basis?)
![image](https://user-images.githubusercontent.com/45246069/118407293-78948300-b680-11eb-9d64-1be9d6c256b8.png)
Renders to:
![image](https://user-images.githubusercontent.com/45246069/118408068-0d4cb000-b684-11eb-9754-c1d841f94fa9.png)
Anki card has a bit of the HTML comment in it.
![image](https://user-images.githubusercontent.com/45246069/118408157-7fbd9000-b684-11eb-8449-8ffbcbc0b904.png)

Similar feature is already used by inline notes:
![image](https://user-images.githubusercontent.com/45246069/118451943-078fb280-b6f6-11eb-8936-fd6da61532d7.png)

The option whether the id should go into a new line could be implemented in the note type table to control it on a per-regex basis. 
![image](https://user-images.githubusercontent.com/45246069/118452339-563d4c80-b6f6-11eb-8f4a-c8b9381d08b2.png)

If it isn't a feature that will be implemented, I could also imagine splitting the giant lists I create when taking notes up using headings and subheadings so that the id comments don't destroy the list.

**Comment by ShootingKing-AM** [comment]
Same bug as #173
