### ISSUE TITLE
Ruled style regex and the Kanban plugin

### ISSUE THREAD

**Issue by kueykuang** [Pseudonium/Obsidian_to_Anki#257]
The kanban plugin has three dashes in the markdown.
![image](https://user-images.githubusercontent.com/86875203/124352213-b732cc80-dc31-11eb-9e3a-7830e0e72b5d.png)

Obsidian to Anki creates a card out of it
![image](https://user-images.githubusercontent.com/86875203/124352234-d16caa80-dc31-11eb-8f45-0cab85d2673e.png)

If you delete that card it will cause an error in your kanban board
![image](https://user-images.githubusercontent.com/86875203/124352256-f8c37780-dc31-11eb-9655-bf66d5c227df.png)

**Comment by kueykuang** [comment]
I somehow solved the problem by deleting the id and whitespace generated by Obsidian to Anki in the markdown

**Comment by christopherAI2022** [comment]
This just happened to me.  How can you avoid it happening in the future though?
