### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by silentdot** [Pseudonium/Obsidian_to_Anki#27]
Hey, 

i found out that your script is running into problems, when facing against some special unicodes. For Example Emojis.

I got this issue fixed by adding a different encoding in your open(file) methods.

```python
open(self.filename, encoding='latin_1')
```
You can find a list of all encodings here: https://docs.python.org/2.4/lib/standard-encodings.html

**Comment by Pseudonium** [comment]
Ok, could you post an example of where the script fails on Emojis?

**Comment by silentdot** [comment]
Added this Emoji in the Heading.
![grafik](https://user-images.githubusercontent.com/24421278/92589235-919b9780-f29a-11ea-99f6-d2e2486bfae9.png)
When i run the script, it runs into this Exception:
![grafik](https://user-images.githubusercontent.com/24421278/92589364-b98afb00-f29a-11ea-832c-610a1f2083ca.png)

**Comment by Pseudonium** [comment]
Ah ok. Does changing the encoding to ‘utf-8’ work? Since that should support all of Unicode.

**Comment by silentdot** [comment]
Yeah, that seems to work. I found out the default encoding on Windows is: 
windows-1252

So that seems to be the problem.

**Comment by Pseudonium** [comment]
Ok then. I’ll push an update that makes the encoding utf-8, which should hopefully work for all characters on all systems.

**Comment by Pseudonium** [comment]
Updated the release to v2.0.1, could you confirm that it works?

**Comment by silentdot** [comment]
Its working! Thanks for the fast fix :)
