### ISSUE TITLE
flashcard in bulleted list does not look clean in edit mode due to wrapped html created code

### ISSUE THREAD

**Issue by ravipawar89** [Pseudonium/Obsidian_to_Anki#276]
![image](https://user-images.githubusercontent.com/11712495/131448740-71d22a4f-a538-410d-b315-4cc4c9232379.png)
as of now the bullet list in obsidian is not breaking(earlier it used to break the whole bulleted list after creation of flashcard), but in edit mode it does not look clean. please can you make the html wrapped tag displayed elsewhere (may be on right side of the created flashcard or elsewhere). this is a suggestion. if this could be implemented then this is the best plugin. i have attached a image showing the issue which I mentioned in the post

**Comment by ShootingKing-AM** [comment]
same as #173
