### ISSUE TITLE
[[Feature request] Its possible to add the logseq flashcard syntax via regex?

### ISSUE THREAD

**Issue by Pvazevedo** [Pseudonium/Obsidian_to_Anki#277]
First, big thx for this great plugin, it's really hand to make flashcard right inside of Obsidian without the need to use anki and getting distracted for changing programs while studying.

The logseq flashcard synthax:

![image](https://user-images.githubusercontent.com/79871889/133090838-6ba79c65-c571-4a46-b5f1-f952659ea94c.png)

![image](https://user-images.githubusercontent.com/79871889/133090944-819657d6-d63c-4062-9a82-6d6a587607f6.png)

**Comment by YuhomC** [comment]
I’m trying to use the add-on"Obsidian to Anki 1" but it cannot detect Logseq generated text properly.
As Logseq is based on bullet outlines. It generates Tab and - at the start of each line even though it’s a blank newline.
This makes it hard to match the add-on style which requires a blank line to separate each card. I still haven’t figured out how to customize the **Regex** to match Logseq.
If you work this out, please let me know !!!

I find [another add-on](https://github.com/debanjandhar12/Obsidian-Anki-Sync.git) to handle this.
The con is the decleration is not that convinent.
The pro is the format stays as it should be.
I do wish the Neuracache flashcard style work for Logseq.
