### ISSUE TITLE
ID appended to the end of tags when using regex

### ISSUE THREAD

**Issue by Joe1177** [Pseudonium/Obsidian_to_Anki#28]
When using tags and the custom regex option the ID is getting appended to the end of the tag. Following [regex Q&A example](https://github.com/Pseudonium/Obsidian_to_Anki/blob/master/regex.md#question-answer-style) with an input file like:
```
Q: How do you use this style?
A: Just like this. Tags: #ObsidianTest




Q: Can the question
run over multiple lines?
A: Yes, and
So can the answer Tags: #ObsidianTest
```
is resulting in
```
Q: How do you use this style?
A: Just like this. Tags: #ObsidianTestID: 1599656251691




Q: Can the question
run over multiple lines?
A: Yes, and
So can the answer Tags: #ObsidianTestID: 1599656251710
```

**Comment by Pseudonium** [comment]
Ah, good catch! I just pushed a fix to the releases (now v2.0.2) - could you confirm if it works?

**Comment by Joe1177** [comment]
Thanks for the quick response! With the following input file:
```
Q: Test 01
A: Without Tag.

Q: Test 02
A: With Tag on same line. Tags: #Hello

Q: Test 03
A: With Tag on line below.
Tags: #Hello

Q: Test 04
A: Last question in file.
```
I am getting now:
```
Q: Test 01
A: Without Tag.

ID: 1599657621668

Q: Test 02
A: With Tag on same line. Tags: #Hello
ID: 1599657621629


ID: 1599657621688

Q: Test 03
A: With Tag on line below.
Tags: #Hello
ID: 1599657621647


Q: Test 04
A: Last question in file.
```

The 'Test 04' card is created with the ID ending in 688, not sure why it's appearing between 'Test 02' and 'Test 03'

**Comment by Pseudonium** [comment]
Yes, I realised this problem was a bit deeper than I thought. Hold on

**Comment by Pseudonium** [comment]
Okay, updated the release to v2.0.3. See if that works?

**Comment by Joe1177** [comment]
Brilliant! 😄 Seems to be working. The only thing I have noticed is that if there isn't a blank line at the end of the file it will append the ID to the last line, e.g.
```
Q: Test A
A: This is the last line in the md file.
```
results in
```
Q: Test A
A: This is the last line in the md file.ID: 1599659440617

```
note that the script adds a new line in after the ID to the md file. 
but if we do have a blank line at the end of the file...
```
Q: Test B
A: This is the last but one line in the md file.

```
it works correctly
```
Q: Test B
A: This is the last but one line in the md file.
ID: 1599659530913

```

**Comment by Pseudonium** [comment]
Okay, updated v2.0.4 so that no newline at end of file doesn't break things. Sorry to bother you so much, could you check if it works on your end?

**Comment by Joe1177** [comment]
Excellent, seems to be working great my end! Thanks for your help and for creating Obsidian_to_Anki!

**Comment by Pseudonium** [comment]
Oh that's great! Thanks for picking up on this bug, you've improved the experience for future users.

**Comment by Pseudonium** [comment]
Ok, this quick fix came back to bite me. Dammit past self...

Essentially, I fixed it by adding a newline each time, but that's now causing problems. Though, it seems like this is no longer an issue with newer versions of the script...

Feel free to reopen this if this is now an issue, I'm removing my hacky fix
