### ISSUE TITLE
Excessive Sync Times when used with Excalidraw Plugin

### ISSUE THREAD

**Issue by niposch** [Pseudonium/Obsidian_to_Anki#288]
This issue occurs when this plugin is used in conjunction with the obsidian excalidraw plugin ⇒ https://github.com/zsviczian/obsidian-excalidraw-plugin
The excalidraw plugin stores the created drawings as .excalidraw.md files and this causes obsidian-to-anki to scan these files.

As these files are simple md files containing a giant json code block in which the excalidraw information is stored, they tend to be rather big files (100'000k characters or more) this leads to first time syncs of these files to take a lot of time.
(have a few of those files in my vault and the anki sync took well over 2 hours and had to be aborted after that)
I do not want to create anki cards from these files and therefore an option to ignore certain files (similar to a .gitignore) file would make it possible to ignore every file ending with .excalidraw.md using this syntax: **/*.excalidraw.md
This would solve the excessive sync time I was experiencing by not scanning the files that cause it.

**Comment by ananthuthilakan** [comment]
> I got a working prototype ignore setting implemented in #289 that addresses this issue

The author is away since Dec 2020 and unlikely to get any update soon.

**Comment by niposch** [comment]
I have provided a prerelease version of the plugin, including the ignore setting feature. Available here: https://github.com/niposch/Obsidian_to_Anki/releases/tag/3.5.0_prerelease1

**Comment by ananthuthilakan** [comment]
> I have provided a prerelease version of the plugin, including the ignore setting feature. Available here: https://github.com/niposch/Obsidian_to_Anki/releases/tag/3.5.0_prerelease1

thank you for the prerelease much appreciated👌

In fact i have followed the method given in this thread https://github.com/Pseudonium/Obsidian_to_Anki/pull/230 to compile your developmental version and tested in a TEST VAULT. 

however didn't really used it in original vault because there was many content linked to ANKI.

Any how escalidraw plugin is amazing i really want to thank you for that.🥰

**Comment by ananthuthilakan** [comment]
today i give it a go in main vault after backing up everything as suggested and Everything works good😊
great work @niposch  🥰🥰

**Comment by AppGo123** [comment]
HI,
I HAD A PROBLEM WITH "OBSIDIAN-TO-ANKI".
WHEN IT HAS THE .excalidraw FILES IT BLOCKS, SO WITH A LITTLE SEARCH I FOUND THIS POST.

I HAVE REPLACED THE FILES 
https://github.com/niposch/Obsidian_to_Anki/releases/tag/3.5.0_prerelease1
IN THE PLUGIN FOLDER BUT IT STILL STOPS, I HAVE TO SPECIFY TO SKIP THE .excalidraw FILES,
IF DOVE

THANK YOU SO MUCH FOR SUPPORTING A PLUGING WHICH UNFORTUNATELY IS NOT UPDATED :)

**Comment by niposch** [comment]
> HI, I HAD A PROBLEM WITH "OBSIDIAN-TO-ANKI". WHEN IT HAS THE .excalidraw FILES IT BLOCKS, SO WITH A LITTLE SEARCH I FOUND THIS POST.
> 
> I HAVE REPLACED THE FILES https://github.com/niposch/Obsidian_to_Anki/releases/tag/3.5.0_prerelease1 IN THE PLUGIN FOLDER BUT IT STILL STOPS, I HAVE TO SPECIFY TO SKIP THE .excalidraw FILES, IF DOVE
> 
> THANK YOU SO MUCH FOR SUPPORTING A PLUGING WHICH UNFORTUNATELY IS NOT UPDATED :)

I've incorporated the recent fixes from this repo in the new release I did a couple of days ago so installing this should make the plugin work again and it includes the ignore setting.
https://github.com/niposch/Obsidian_to_Anki/releases/tag/3.5.0_prerelease2

**Comment by AppGo123** [comment]
it works again :))
Thank you
how do I add other files or paths to ignore just use comma or semicolon **/*.excalidraw.md, file.md

**Comment by niposch** [comment]
one patter per line. So you could do:
```
**/*.excalidraw
Home.md
templates/*
```
