### ISSUE TITLE
Spaces after TARGET DECK or FILE TAGS

### ISSUE THREAD

**Issue by Joe1177** [Pseudonium/Obsidian_to_Anki#29]
Not sure if this is more user error rather than an issue but if there are any spaces after TARGET DECK or FILE TAGS then Obsidian_to_Anki ignores the line, e.g.
```
TARGET DECK 
Test
```
would not be recognised by the script as there is a space after the word 'DECK'.

Note: copy & pasting from the [readme](https://github.com/Pseudonium/Obsidian_to_Anki#tag-formatting) example in my browser resulted in spaces after TARGET DECK being included.

**Comment by Pseudonium** [comment]
Ah ok. The way I have the regex set up, you do need a newline straight after TARGET DECK or FILE TAGS, yeah. I think I've now removed the whitespace from the documentation - could you check if that works now?

**Comment by Joe1177** [comment]
Yep, copying and pasting from the example no longer has a space included. Maybe worth a note in the readme somewhere (Syntax section?) that it shouldn't have any spaces at the beginning/end or other formatting etc.? p.s. Stick a donation link in too 🙂 !

**Comment by Pseudonium** [comment]
Okay, so I've updated the documentation in the syntax section to make clear that an exact match is required.

Not sure how I'd put a donation link in (GitHub sponsors?), but thank you for your kind words!
