### ISSUE TITLE
Does the author gone?

### ISSUE THREAD

**Issue by YukoOshima** [Pseudonium/Obsidian_to_Anki#296]
I found that the plugin hasn't been updated for a long time. 
Is it still being maintained?

**Comment by 23727** [comment]
Good question, @YukoOshima. I was also wondering the same thing

**Comment by YukoOshima** [comment]
> Good question, @YukoOshima—I was also wondering the same thing.
> 
> The plug-in appears to be pretty stable during the first few days I have been using it. How is your experience with it?

I agree with you. The plugin is stable. But I just worry a little about the plugin because it's not been updated for a long time. haha.
