### ISSUE TITLE
Not able to generate cards. 

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#31]
I tried writing a test file:
```

    TARGET DECK
    Default
    START
    Basic 
    Front: Who declares Globally Important Agricultural Heritage Systems?
    Back: FAO
    Food and Agriculture Organisation
    Tags: Economics::Sectors::Agriculture
    END
```

Ran the Obsidian\_to\_Anki.py script. The script runs "successfully". I get no cards in the ANKI. What am I doing wrong?

(ANKIConnect was working)

Edit: Tried running on your [test.md](https://test.md) too. Didnt work. There must be something I am missing. :/

Doesn't work for me at all!

Here are the steps I followed:

1. Installed ANKIConnect. Checked if it works. It does.
2. Installed markdown from pip (it was already there)
3. Kept the .py file in a directory, ran the code. it generated config.ini file.
4. Then made one sample text markdown as shows above. Ran the code again, didn't get any new cards in my ANKI.
5. ANKI was running the whole time.
Where did I go wrong?

**Comment by Pseudonium** [comment]
Ok, I just copy-pasted the file you provided into a markdown file and ran the script on it, it added the cards to Anki fine.
What version of the script are you running?
Also, have you tried running the script on the file again (perhaps with the file no longer open in Notepad or whatever)?

**Comment by dummifiedme** [comment]
I don't know exactly what I am missing.
Version number is whatever latest it was yesterday. I will check and update later on.

Yes, I had tried multiple times. It didn't work for me.

**Comment by Pseudonium** [comment]
Could you show me the command-line output of the script?

**Comment by dummifiedme** [comment]
![image](https://user-images.githubusercontent.com/68785729/92994398-843f1100-f517-11ea-9097-efa4108ee679.png)

**Comment by dummifiedme** [comment]
![image](https://user-images.githubusercontent.com/68785729/92994417-a89aed80-f517-11ea-9482-d3f6c4009723.png)

**Comment by Pseudonium** [comment]
I see the problem. You aren't running the script on the file - you're just running the script. Try adding `test.md` to your command.

**Comment by dummifiedme** [comment]
Ohh..OKay

**Comment by Pseudonium** [comment]
If you wanted to do that, you can add `.` to the command (signals that the script will attempt to do all files in a directory, and `.` signals the current directory)

**Comment by dummifiedme** [comment]
![image](https://user-images.githubusercontent.com/68785729/92994512-67570d80-f518-11ea-800b-fc5660cd69a2.png)
When I added Test.md

**Comment by dummifiedme** [comment]
Got it. It's functional now! :)

**Comment by Pseudonium** [comment]
Great! I'll make sure that the script shows a help message if called with no arguments in the next update.
