### ISSUE TITLE
Cloze Paragraph style regex is not converted

### ISSUE THREAD

**Issue by Nadir-Echo** [Pseudonium/Obsidian_to_Anki#316]
The configuration of the plugin includes regular expressions, and the CurlyCloze button is also enabled.
After input according to the format, the ID number will be displayed, #flashcard is completely valid, but the conversion of fill-in-the-blank questions can only follow the Anki syntax format of {{}}
, once the format of the plug-in is used, it cannot be converted, the card shows that the blank cannot be found, and the card is still {} instead of {{}}

![image](https://user-images.githubusercontent.com/86950349/153130903-464e478d-20e3-4b8b-ad08-0b8be9885a34.png)
![image](https://user-images.githubusercontent.com/86950349/153130938-1e7255e1-a298-4913-b316-ccbe58c0d6a8.png)
![image](https://user-images.githubusercontent.com/86950349/153130951-f2909de0-7a93-4b11-a774-9d962f230a5a.png)
![image](https://user-images.githubusercontent.com/86950349/153130965-5e033947-f8b3-40b1-ba3e-c53678eaab29.png)

**Comment by Nadir-Echo** [comment]
> The configuration of the plugin includes regular expressions, and the CurlyCloze button is also enabled. After input according to the format, the ID number will be displayed, #flashcard is completely valid, but the conversion of fill-in-the-blank questions can only follow the Anki syntax format of {{}} , once the format of the plug-in is used, it cannot be converted, the card shows that the blank cannot be found, and the card is still {} instead of {{}}
> 
> ![image](https://user-images.githubusercontent.com/86950349/153130903-464e478d-20e3-4b8b-ad08-0b8be9885a34.png) ![image](https://user-images.githubusercontent.com/86950349/153130938-1e7255e1-a298-4913-b316-ccbe58c0d6a8.png) ![image](https://user-images.githubusercontent.com/86950349/153130951-f2909de0-7a93-4b11-a774-9d962f230a5a.png) ![image](https://user-images.githubusercontent.com/86950349/153130965-5e033947-f8b3-40b1-ba3e-c53678eaab29.png)

![image](https://user-images.githubusercontent.com/86950349/153131595-b121169a-9896-4468-b8f2-76892e0375c0.png)
![image](https://user-images.githubusercontent.com/86950349/153131646-b10e7e2c-6e88-412d-accb-6bc8b405de32.png)
![image](https://user-images.githubusercontent.com/86950349/153131667-45e7e770-4208-45f1-a00f-c0784d14b36d.png)


Copying the example from github to obsidian gives an error, I'm not sure if this is causing it
![image](https://user-images.githubusercontent.com/86950349/153132108-e1aa7e29-84d8-4ea4-bcc8-015aae9434cf.png)
app.js:1 Uncaught TypeError: Cannot read property 'type' of undefined
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2525:26)
    at e.t.tryTrigger (app.js:1)
    at e.t.trigger (app.js:1)
    at e.trigger (app.js:1)
    at t.handlePaste (app.js:1)
    at Object.paste (app.js:1)
    at t.runCustomHandlers (app.js:1)
    at HTMLDivElement.<anonymous> (app.js:1)

**Comment by Nadir-Echo** [comment]
![image](https://user-images.githubusercontent.com/86950349/153134981-41013788-0def-47cb-ae2f-436b8b1dae17.png)

VM172:30759 Failed to add note {deckName: “English”, modelName: “填空题”, fields: {…}, options: {…}, tags: Array(2)}deckName: "English"fields: {文字: “alsdjflksadjfklsajd{aklsdjflksdajf}
\nlakdsjfklsajfk{sladkjflskdaj}”, back: “”}modelName: "填空题"options: {allowDuplicate: false, duplicateScope: “deck”}tags: (2) [“Obsidian_to_Anki”, “”]proto: Object in file Study/English/未命名.md due to error cannot create note because it is empty
parse_requests_1 @ VM172:30759
requests_1 @ VM172:30722
async function (async)
requests_1 @ VM172:30721
scanVault @ VM172:30959
async function (async)
scanVault @ VM172:30949
eval @ VM172:30995

**Comment by Nadir-Echo** [comment]
I roughly seem to have found the problem. It is useful to use it in the Anki note template whose note type contains Cloze, but the problem is that I created a new template named Cloze ALL, but it was still created in the original template with Chinese "填空题". Under the template, I changed the name of the original fill-in-the-blank template to English "Cloze", and the card was not generated directly. When I opened the debugging platform, it showed that the modelName could not be found: "填空题"
![image](https://user-images.githubusercontent.com/86950349/153160655-f240528f-bf09-43a9-9434-4aafdd14d2cc.png)
Object
deckName: "English"
fields: {文字: "kasjdflkjdsk {alskdjgfklsadjf} sfagdsfg", back: ""}
modelName: "填空题"
options: {allowDuplicate: false, duplicateScope: "deck"}
tags: (2) ["Obsidian_to_Anki", ""]
__proto__: Object

Where do I need to set it up?

**Comment by Nadir-Echo** [comment]
已解决

**Comment by feixiangdao** [comment]
> 已解决

请问是怎么解决的？

**Comment by Nadir-Echo** [comment]
> > 已解决
> 
> 请问是怎么解决的？

我有点忘了,我提供几个我隐约还有印象的点吧.一个可能是格式设定上面就是插件里面的设置可能存在问题,你要去对照一下.要么是重置,直接下个英文版Anki的.其他的可以试试清一下插件的缓存
