### ISSUE TITLE
Cloze Deletions not working with provided regex

### ISSUE THREAD

**Issue by adamcole123** [Pseudonium/Obsidian_to_Anki#318]
I have this text:

```{User creates request for resource}  {Orchestrator Web API}  {Orchestrator picks best server rack}  {Network Switch}  {Server}  {Fabric Controller creates resource}  {User can connect to resource}```

With this regex:
```((?:.+\n)*.*\s(?=\{\s+|\{.\d+\:|\{\d+\:)(?:[^\n][\n]?)+)```

I have seen others say that this works for them, why doesn't it work for me? (for reference, I have turned on the settings to allow cloze deletions with curly braces and highlighting)

**Comment by TinyAtoms** [comment]
You want this regex: `((?:.+\n)*(?:.*{.*)(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)`
As specified here: https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Cloze-Paragraph-style

**Comment by timblaktu** [comment]
@TinyAtoms @adamcole123 The documented regex for Cloze-Paragraph-style  works fine for me. However, the [documented highlight-cloze style](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Cloze-Paragraph-style#highlight-cloze-style-obsidian-plugin-only) **_does not._** I'm curious if you could lend some extra pairs of eyes to check my work:

1. *Cloze* Custom Regex in Note type table: `((?:.+\n)*(?:.*==.*)(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)`
    * copied from [here](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Cloze-Paragraph-style#highlight-cloze-style-obsidian-plugin-only)
2. *CurlyCloze - Highlights to Clozes* in ENABLED.
3. Added the following markdown to a file in my Vault, and _Sync Vault_:

```
IPSEC provides ==Authentication==
```

..I get all the expected successful notifications about the sync, but nothing appears in my target Anki deck (Default).

I have vetted my setup using Basic regex cards using the [documented Sub-header style](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Header-paragraph-style#subheader-paragraph-style) which  creates cards just fine, as do basic and non-regex cloze types.

So, seems there's an issue with the documented regex. Putting the faulty regex and my test line from above into regex101.com, I see there is a single match group, matching the entire string:

![image](https://user-images.githubusercontent.com/12355715/171299555-3ed6d123-d739-4550-8838-5163f67f46b4.png)

..and looking at the [docs for writing custom regexes in this plugin](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Regex#custom-styles), it says:

> You need to have as many capture groups in your regexp as there are fields in the note type

.. and [the Anki docs for cloze-deletion](https://docs.ankiweb.net/editing.html#cloze-deletion) implies that for the cloze note type there is only a single field, so *I think (?)* this regex/match should be as expected. Do **_you_** see anything wrong here?

**Comment by timblaktu** [comment]
The problem was that I didn't have ***BOTH*** CurlyCloze Obsidian_to_anki plugin settings enabled:

![image|690x116](upload://uRpFs7l4Q1Ptc8WV8kCi0l5cv1r.png)

The [docs for the highlight cloze style](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Cloze-Paragraph-style#highlight-cloze-style-obsidian-plugin-only) don't make it clear that both are required.

I'd love to update the GitHub repo Wiki to make this more clear, but it does not appear to be editable by me, nor does the wiki appear to be in the repo, so I cannot edit it via a PR from a repo fork. Any suggestions on how to contribute here?

**Comment by TinyAtoms** [comment]
I have never done that before, but here are several options described https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by adamcole123** [comment]
Hi @timblaktu, what you described here doesn't work for me and i think i have the right settings enabled. Could you post a screenshot of what your note looks like please? So that i can compare

**Comment by adamcole123** [comment]
Just fixed it, i clicked these two buttons after changing the settings
![image](https://user-images.githubusercontent.com/32772788/190861975-964c2847-b33f-4b02-9668-3680fabb4e0c.png)
