### ISSUE TITLE
Cannot see the option to add custom regex in Obsidian app

### ISSUE THREAD

**Issue by 1stprinciples** [Pseudonium/Obsidian_to_Anki#319]
I am trying to use the Obsidian_to_Anki plugin on obsidian to add cards to my Anki. I want to use a custom regex to add cards (using the Remote) style. But in the plugin settings I don't see the option to add custom regex

<img width="741" alt="image" src="https://user-images.githubusercontent.com/40528731/157211371-3354f10e-cf77-4742-8de7-419221c75e9d.png">

<img width="742" alt="image" src="https://user-images.githubusercontent.com/40528731/157211389-f98d28ff-a7b6-4d74-ac24-ad4b2132c102.png">

**Comment by Borouch** [comment]
Press on `note type table`. It is bad UI as it is not indicated as clickable.
