### ISSUE TITLE
Examples, docs, screenshots

### ISSUE THREAD

**Issue by arielaco** [Pseudonium/Obsidian_to_Anki#33]
It'd be great if you could include that, as they're doing here: https://github.com/kangruixiang/Ankify

**Comment by Pseudonium** [comment]
Ok. I have tried to do that with the newer syntax in v2, in the [regex.md](regex.md) file, but I could try and add some more concrete examples in the default syntax.

**Comment by Pseudonium** [comment]
I have been meaning to make a tutorial at some point...

**Comment by arielaco** [comment]
Oh didn't catch that! Much clearer. Thank you! 

I simply mention this since I'm sure it may impact adoption.

**Comment by Pseudonium** [comment]
Ah no worries! I'll keep this issue open till I've added some more images/made docs clearer

**Comment by Pseudonium** [comment]
I've made some more progress on this by visibly showing examples of custom syntax on README, but I've still got to do that for the default syntax.

**Comment by Pseudonium** [comment]
@arielaco In the development branch, I've massively cut down on the size of the README file, instead moving everything to a new project wiki! Still need to do images for default syntax, but this should hopefully make navigating much clearer.

**Comment by Pseudonium** [comment]
I've added a small number of images now. I think I'll close this issue, but feel free to reopen it if there are other places you feel would benefit from some pictures.
