### ISSUE TITLE
Obsidian freezing after scanning vault

### ISSUE THREAD

**Issue by TempDR4169** [Pseudonium/Obsidian_to_Anki#397]
Obsidian window becomes unresponsive after clicking the Scan Vault button on the side bar. Notifications appea but do not disappear.

**Comment by yonggithub** [comment]
same to me

**Comment by TempDR4169** [comment]
I found a fix. The issue happens due to when images are pasted alongside text causing all of the image data to be pasted as data:image therefore when syncing the program has to scan through all of the data causing the program to freeze because of the amount of data it has to scan through

**Comment by Solarrixs** [comment]
This also occurs if you have Excalidraw files. What I do is just bring them out of the Obsidian vault, sync, and then bring them back in.

**Comment by lsolesen** [comment]
Excalidraw by @zsviczian files also have these open issues #350 #439.

**Comment by niposch** [comment]
related for excalidraw files #288 and #289

**Comment by zsviczian** [comment]
You may want to try turning on compression of Excalidraw files in plugin settings. I originally built the compression for avoiding Excalidraw JSON from turning up in Obsidian Search, but I can imagine that it may be able to help with Anki indexing as well.

![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/14358394/3b03571a-0805-44ae-9172-9361a47e4723)


Additionally I wonder if Anki offers filtering based on frontmatter properties or tags. That could be used to influence indexing.

In addition anki could use the `ExcalidrawAutomate.isExcalidrawFile(file:TFile)` function to filter out Excalidraw files. Just add "obsidian-excalidraw-plugin": "1.9.14" to dev dependencies and use the getEA() function.
![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/14358394/38986476-f83a-4e0f-93a3-bfe4bd4c006d)
