### ISSUE TITLE
Error while synching

### ISSUE THREAD

**Issue by siraj-samsudeen** [Pseudonium/Obsidian_to_Anki#398]
When I try to sync, I get this error. 

![image](https://user-images.githubusercontent.com/11910293/214756366-e1d8cbdb-d697-48b2-808a-e129ec854bcb.png)

Obsidian version: Version 1.1.12 (Installer 0.15.9)

Plugin Version: 
![image](https://user-images.githubusercontent.com/11910293/214756443-d50539ab-a808-4770-aa9d-ebaeb74d7f40.png)

Is this an issue caused by any recent upgrade of Obsidian?

**Comment by josegaert** [comment]
I've been a faithful user of this plugin since the very beginning and I've never had problems. Now, I've run into the same issue. I fear we will not be alone.

**Comment by josegaert** [comment]
I'm not 100% sure that I don't introduce other problems but this change in the code seems to fix it.
In the file [\src\files-manager.ts](https://github.com/Pseudonium/Obsidian_to_Anki/blob/master/src/files-manager.ts)
If somebody could verify, that would be great.
From:
```
    getFolderPathList(file) {
        let result = [];
        let abstractFile = file;
        while (abstractFile.hasOwnProperty('parent')) {
            result.push(abstractFile.parent);
            abstractFile = abstractFile.parent;
        }
        result.pop(); // Removes top-level vault
        return result;
    }
```
To:
```
    getFolderPathList(file) {
        let result = [];
        let abstractFile = file;
        while (abstractFile != null && abstractFile.hasOwnProperty('parent')) {
            result.push(abstractFile.parent);
            abstractFile = abstractFile.parent;
        }
        result.pop(); // Removes top-level vault
        return result;
    }
```

**Comment by siraj-samsudeen** [comment]
That is brilliant - can you please let me know where the source files are
stored. I am on a Mac. I would try this fix as it seems like a logical
thing to do :)

**Comment by josegaert** [comment]
In the main folder of your vault you have a hidden folder `.obisidan` The plugin code is situated there. You need to change the file `.obsidian/plugins/obsidian-to-anki-plugin/main.js`. The line that needs to be changed is line 30603, at least on my computer. 

Of course this is not a sustainable way of working. If this is an error that showed up with a recent release (I have not done any extensive testing) then all of us are affected. The only stable way seems that this project gets a new maintainer.

**Comment by Shadow9881** [comment]
Had the same Problem, since I updated to 1.1.12. Your code fixed it. Thank you @josegaert !

**Comment by siraj-samsudeen** [comment]
That is wonderful Jo - the instruction was perfect. After changing the code
and restarting, it worked well. Cards are now synching...

Regarding the question for a new maintainer, what would be the knowledge
required to become a contributor to this project? Since I use the plugin
for a long time, I would love to step in to do some contribution, but I am
afraid whether my skills would measure up...

**Comment by Luiz-nyan** [comment]
Worked per

> I'm not 100% sure that I don't introduce other problems but this change in the code seems to fix it. In the file [\src\files-manager.ts](https://github.com/Pseudonium/Obsidian_to_Anki/blob/master/src/files-manager.ts) If somebody could verify, that would be great. From:
> 
> ```
>     getFolderPathList(file) {
>         let result = [];
>         let abstractFile = file;
>         while (abstractFile.hasOwnProperty('parent')) {
>             result.push(abstractFile.parent);
>             abstractFile = abstractFile.parent;
>         }
>         result.pop(); // Removes top-level vault
>         return result;
>     }
> ```
> 
> To:
> 
> ```
>     getFolderPathList(file) {
>         let result = [];
>         let abstractFile = file;
>         while (abstractFile != null && abstractFile.hasOwnProperty('parent')) {
>             result.push(abstractFile.parent);
>             abstractFile = abstractFile.parent;
>         }
>         result.pop(); // Removes top-level vault
>         return result;
>     }
> ```

Worked perfectly, thank you!
