### ISSUE TITLE
Plugin doesn't genereate the ID links

### ISSUE THREAD

**Issue by marastoniarts** [Pseudonium/Obsidian_to_Anki#407]
Hi, since the last update of Obsidian v1.1.15 the Obsidian_to_Anki doesn't work anymore.
The plugin connects with Anki successfully, but doesn't generate the ID info for the new cards. The Obsidian plugin and Anki extension are both enabled, and the Anki is open during the sync process.
The plugin was working fine today before the Obsidian update.

**Comment by 29yabuki** [comment]
Did you have the same error as below?
<img width="471" alt="image" src="https://user-images.githubusercontent.com/66338663/220721269-eddcf6ff-1a98-41e1-a7e1-730b6b69b4cf.png">

Mine worked perfectly too before the update

**Comment by marastoniarts** [comment]
> Did you have the same error as below? <img alt="image" width="471" src="https://user-images.githubusercontent.com/66338663/220721269-eddcf6ff-1a98-41e1-a7e1-730b6b69b4cf.png">
> 
> Mine worked perfectly too before the update

Where can I find the error log? For me the plugin doesn't show a crash message, just doesn't complete the sync process.

**Comment by 29yabuki** [comment]
If you're using Windows, do ctrl + shift + i then the console will appear.

**Comment by romankrru** [comment]
@29yabuki I have same error as you. Plugin is broken after Obsidian v1.1.15 update

**Comment by BenjaminOyarzun17** [comment]
> Did you have the same error as below? <img alt="image" width="471" src="https://user-images.githubusercontent.com/66338663/220721269-eddcf6ff-1a98-41e1-a7e1-730b6b69b4cf.png">
> 
> Mine worked perfectly too before the update

hi, same issue here. I am also getting the exact same error log in the console.

**Comment by BenjaminOyarzun17** [comment]
> 

worked for me, thanks!

**Comment by Solarrixs** [comment]
> > 
> 
> worked for me, thanks!

Did you follow the steps as stated by @romankrru? It did not work for me, sadly.

**Comment by romankrru** [comment]
@Solarrixs try to restart obsdiain

**Comment by reizen-desu** [comment]
> Here is the quick and dirty fix:
> 
> 1. Go to your obsidian vault folder
> 2. Open `/.obsidian/plugins/obsidian-to-anki-plugin/main.js` with any text editor
> 3. Replace line 30603
> 
> ```
>         while (abstractFile.hasOwnProperty('parent')) {
> ```
> 
> with
> 
> ```
>         while (abstractFile && abstractFile.hasOwnProperty('parent')) {
> ```
> 
> 4. Restart obsidian
> 
> I haven't tested it thoroughly but it looks like this fixes the issue

This also fixed it for me. Thanks @romankrru

**Comment by Angelawu867** [comment]
It didn't work for me as well.

**Comment by Solarrixs** [comment]
> It didn't work for me as well. 

It worked for me after restarting PC.

**Comment by Angelawu867** [comment]
I tried all of that and it still doesn't generate the ID

**Comment by Ali-C-Ila** [comment]
> Here is the quick and dirty fix:

Thanks for the emergency patch, but I worry about the stability in the long run. I don't know coding at all, but is this really a "proper" way to write code?

**Comment by romankrru** [comment]
> I worry about the stability in the long run

This concern is understandable. The proper way would be to make a pull request and release a new version of the plugin. But this project seems to be unmainted. From the look of the github activity, @Pseudonium  has been inactive for more than a year. 

I have tried other anki/srs plugins and unfortunately none of them provides required flexibility and usability for me. 

Hopefully someone would commit to maintain the fork of this project or the maintainer would return to github.

**Comment by beresarus** [comment]
> Here is the quick and dirty fix:
> 
> 1. Go to your obsidian vault folder
> 2. Open `/.obsidian/plugins/obsidian-to-anki-plugin/main.js` with any text editor
> 3. Replace line 30603
> 
> ```
>         while (abstractFile.hasOwnProperty('parent')) {
> ```
> 
> with
> 
> ```
>         while (abstractFile && abstractFile.hasOwnProperty('parent')) {
> ```
> 
> 4. Restart obsidian
> 
> I haven't tested it thoroughly but it looks like this fixes the issue

**romankrru** thank you very much for your help! Everything works with you help.

**Comment by marastoniarts** [comment]
> Here is the quick and dirty fix:
> 
>     1. Go to your obsidian vault folder
> 
>     2. Open `/.obsidian/plugins/obsidian-to-anki-plugin/main.js` with any text editor
> 
>     3. Replace line 30603
> 
> 
> ```
>         while (abstractFile.hasOwnProperty('parent')) {
> ```
> 
> with
> 
> ```
>         while (abstractFile && abstractFile.hasOwnProperty('parent')) {
> ```
> 
>     4. Restart obsidian
> 
> 
> I haven't tested it thoroughly but it looks like this fixes the issue

Thank you very much! Works like a charm!

**Comment by marastoniarts** [comment]
@Angelawu867 @beresarus @romankrru Hey guys, this workaround is still working for you? It worked only for the 1st batch of my cards, the second time that I tried sync new cards shows even the message of adding media and file hashes, but stopped generating the ID.
![error log](https://user-images.githubusercontent.com/91513334/221303110-6ac7c5ce-0f3f-4636-b543-cff2c5b4ad2b.PNG)

**Comment by beresarus** [comment]
**marastoniarts**, yesterday made changes to `/.obsidian/plugins/obsidian-to-anki-plugin/main.js` file of the plugin. Everything works fine.
I think your problem is most likely in another.

But to make sure of this, delete the current version of Obsidian. If you have Windows installed, delete folder C:\Users\user\AppData\Roaming . Turn off the Internet, install obsidian v.1.1.9, disable the automatic update option in the settings, turn on the Internet, install the plugin ObsidianToAnki and check.

**Comment by lucascrlsn** [comment]
Works for me as well!

**Comment by drrager** [comment]
> Here is the quick and dirty fix:
> 
> 1. Go to your obsidian vault folder
> 2. Open `/.obsidian/plugins/obsidian-to-anki-plugin/main.js` with any text editor
> 3. Replace line 30603
> 
> ```
>         while (abstractFile.hasOwnProperty('parent')) {
> ```
> 
> with
> 
> ```
>         while (abstractFile && abstractFile.hasOwnProperty('parent')) {
> ```
> 
> 4. Restart obsidian
> 
> I haven't tested it thoroughly but it looks like this fixes the issue

Sorry to be a total noob, but how do I find this file? I'm on Mac and I checked my vault folder but didn't find the file you mentioned.

**Comment by drrager** [comment]
I updated to version 1.1.15 today, which broke the plugin, and this fix didn't work for me. Does anyone know how I can revert to the previous version of Obsidian? I'm afraid that might be the only way to go back to my workflow.

**Comment by Solarrixs** [comment]
@drrager yes, having excalidraw files breaks the plugin - it'll take very long for it to scan. what i do is move the excalidraw folder or files out.

i know its not ideal, but as said above, unless someone commits 
to this plugin, we will need to rely on workarounds.

**Comment by drrager** [comment]
> @drrager yes, having excalidraw files breaks the plugin - it'll take very long for it to scan. what i do is move the excalidraw folder or files out.
> 
> i know its not ideal, but as said above, unless someone commits to this plugin, we will need to rely on workarounds

How long has that been the case for you? I've been using Excalidraw and Obsidian to Anki together for almost a year, but only now am I running into problems

**Comment by Solarrixs** [comment]
> > @drrager yes, having excalidraw files breaks the plugin - it'll take very long for it to scan. what i do is move the excalidraw folder or files out.
> > 
> > i know its not ideal, but as said above, unless someone commits to this plugin, we will need to rely on workarounds
> 
> How long has that been the case for you? I've been using Excalidraw and Obsidian to Anki together for almost a year, but only now am I running into problems

Just started excali 2 weeks ago and started 2 weeks ago (immediately)

**Comment by ViktorKensen** [comment]
im no coding expert, how do i fix this? Where is the folder im looking for? Thanks in advance!

**Comment by romankrru** [comment]
> im no coding expert, how do i fix this? Where is the folder im looking for? Thanks in advance!

Follow the steps described in https://github.com/Pseudonium/Obsidian_to_Anki/issues/407#issuecomment-1440645025

If you can't find your vault location then it is easy to see if you click `Open another vault` icon in the bottom left corner and then in the popup windows you will see your vault location on the left.

You might not be able to see `.obsidian` folder in your vault if you are on mac/linux because the file manager might hide files starting with the dot. In this case google how to show hidden files on your system

**Comment by Rri-bit** [comment]
I'm not a tech-savvy either :((
Downgraded Obsidian to 1.1.9, and the plugin seems to connect, but nothing eventually happens and obsidian just freezes. 
Any advice/recommendation, please?

**Comment by Solarrixs** [comment]
> I'm not a tech-savvy either :((
> Downgraded Obsidian to 1.1.9, and the plugin seems to connect, but nothing eventually happens and obsidian just freezes. 
> Any advice/recommendation, please?

Do you have excali draw, read up for recommended steps if you do have it

**Comment by Rri-bit** [comment]
Actually, I don't

I reinstalled the plugin again, and it acts like it works, but there are no new flashcards created in Anki. Interesting......

**Comment by Rri-bit** [comment]
Update: it finally worked after downgrading to 1.1.9 (as described above) and reinstalling(!!) the plugin.
Many-many thanks!

**Comment by CTCSU** [comment]
> Here is the quick and dirty fix:
> 
>     1. Go to your obsidian vault folder
> 
>     2. Open `/.obsidian/plugins/obsidian-to-anki-plugin/main.js` with any text editor
> 
>     3. Replace line 30603
> 
> 
> ```
>         while (abstractFile.hasOwnProperty('parent')) {
> ```
> 
> with
> 
> ```
>         while (abstractFile && abstractFile.hasOwnProperty('parent')) {
> ```
> 
>     4. Restart obsidian
> 
> 
> I haven't tested it thoroughly but it looks like this fixes the issue

Thanks very much! This works for me.

I'm wondering if we have any approach to push such changes to master? I'd like to maintain it, but seems the code owner has been missing for a long time.

**Comment by ChmielewskiKamil** [comment]
@romankrru 
You are a goddamn genius. Thank you so much, my saviour!

**Comment by lgoppelt** [comment]
@romankrru
Worked for me as well. Thank you Sir.

**Comment by ShootingKing-AM** [comment]
This is fixed now in latest release. Can be closed as solved. 

(cc: @Pseudonium)
