### ISSUE TITLE
Invalid string length on syncronisation. Developer Console pauses before potential out-of-memory

### ISSUE THREAD

**Issue by MisterPresident** [Pseudonium/Obsidian_to_Anki#408]
Hey,
I'm getting the following error after I press the sync button:
![image](https://user-images.githubusercontent.com/11216162/220886819-3aca9c67-33fa-45ae-a09f-289b605e9ae1.png)
To narrow down the error, I created only one card:
`STARTI [Basic] This is a test. Back: Test successful! ENDI `
It gets generated:
`STARTI [Basic] This is a test. Back: Test successful! <!--ID: 1677148389236--> ENDI`
However, if I press the sync button again, Obsidian dies with the error stated above.
Any help appreciated.
Thanks

**Comment by crabbystacks** [comment]
I am having the same issue.
