### ISSUE TITLE
Cannot scan vault: TypeError: Cannot read properties of null (reading 'hasOwnProperty')

### ISSUE THREAD

**Issue by alexagedah** [Pseudonium/Obsidian_to_Anki#409]
Environment : obsidian 1.1.12; anki 2.1.56
After setting up obsidian to anki and trying to scan the vault, I get the following message in the vault

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'hasOwnProperty')
at FileManager.getFolderPathList (plugin:obsidian-to-anki-plugin:30603:29 )
at FileManager.dataToFileData (plugin:obsidian-to-anki-plugin:30634:39)
at FileManager.genAllFiles (plugin:obsidian-to-anki-plugin:30651:36)
at async FileManager.initialiseFiles (plugin:obsidian-to -anki-plugin:30656:9)
at async MyPlugin.scanVault (plugin:obsidian-to-anki-plugin:30958:9)
at async HTMLDivElement.eval (plugin:obsidian-to-anki-plugin:30995:13)

<img width="1035" alt="Screenshot 2023-02-23 at 18 59 18" src="https://user-images.githubusercontent.com/108612856/221004336-17d171ec-3042-4051-b267-e68d13a8ce9c.png">

EDIT:
I looked around on the internet and found this (thank you google translate lol)

https://forum-zh.obsidian.md/t/topic/14838

The fix the guy suggests actually works.

**Comment by alexagedah** [comment]
I looked around on the internet and found this (thank you google translate lol)

https://forum-zh.obsidian.md/t/topic/14838


The fix the guy suggests actually works.

**Comment by ShootingKing-AM** [comment]
Thanks !

**Comment by Ali-C-Ila** [comment]
I think this is the same as #407 .

**Comment by ShootingKing-AM** [comment]
Since the author is not responsive, I made a minor release here: https://github.com/ShootingKing-AM/Obsidian_to_Anki/releases/tag/3.4.2, you can try that for people who are not coders.

**Comment by GBergatto** [comment]
I'll write the instructions here to make them more easily accessible.

1. From your vault, navigate to `.obsidian/plugins/obsidian-to-anki-plugin`
2. Open the file `main.js`
3. Look for the line  `while (abstractFile.hasOwnProperty('parent'))`
4. Change it to `while (abstractFile && abstractFile.hasOwnProperty('parent')) {`

**Comment by dd1512** [comment]
> I'll write the instructions here to make them more easily accessible.
> 
>     1. From your vault, navigate to `.obsidian/plugins/obsidian-to-anki-plugin`
> 
>     2. Open the file `main.js`
> 
>     3. Look for the line  `while (abstractFile.hasOwnProperty('parent'))`
> 
>     4. Change it to `while (abstractFile && abstractFile.hasOwnProperty('parent')) {`


This seems to fix it but for me it still does not generate the link ID even all there's no error in the Console logs. 
FYI I'm using obsidian 1.1.16

**Comment by ShootingKing-AM** [comment]
You seem not to do it properly i guess, are you sure you are pointing to the correct line (console shows 30603 or something your code is on 503xx line)? Just use the release aforementioned https://github.com/Pseudonium/Obsidian_to_Anki/issues/409#issuecomment-1452292243 it must be much easier and straightforward

**Comment by ShootingKing-AM** [comment]
https://github.com/ShootingKing-AM/Obsidian_to_Anki/issues/9#issuecomment-1453365423 installation instructions are here

**Comment by ShootingKing-AM** [comment]
> Ok, thanks. And how do you access the file `.obsidian/plugins`? Trought the terminal? Because I don't find it in the application or my vault 😕 <img alt="image" width="735" src="https://user-images.githubusercontent.com/60276746/225128211-7baff359-5a19-43da-93cd-5e424af0bd2f.png">

It is 100% there in your vault, <vault root>/.obsidian, because it has a starting '.' you are not able to see it. You need to somehow open it via terminal or 'show hidden folders' etc. Google how to view '.' files or directories on your OS (macos).

**Comment by HeeiYa** [comment]
I have done this, and it worked. it shows "ALL done !..." but actually there is no update in anki. I have no idea how to fix it....

**Comment by ShootingKing-AM** [comment]
> I have done this, and it worked. it shows "ALL done !..." but actually there is no update in anki. I have no idea how to fix it....

Then its a different issue, the solution is related if you see `Cannot scan vault: TypeError: Cannot read properties of null (reading 'hasOwnProperty')` error only when you press ctrl+shift+i

**Comment by Pseudonium** [comment]
Well, it seems this issue has finally bubbled up to start causing errors for me, too...

Sorry for the unresponsiveness, uni terms do get busy. I'll take a look through and see what's causing the errors, hopefully the fix you mentioned here works...

**Comment by jaymaleoca** [comment]
@Pseudonium , oh gosh - I'm glad to see your response. In the past year or so, I have honestly wondered many times if you're okay and if something happened to you. Looks like you're probably busy with university. Anyway, hope you're doing well.
