### ISSUE TITLE
Freezing after using the scan vault command ( and how to solve it.)

### ISSUE THREAD

**Issue by Ali-C-Ila** [Pseudonium/Obsidian_to_Anki#416]
edit: also see #439 

Took a hell lot of time debugging this. Hope my sharing might help some people.❤️

## problem
After using the scan vault command, the whole obsidian program freezes, unresponsive to any action.

## how to solve it 
1. Restart Obsidian.
2. Press Ctrl+Shift+I to open developer tools.
3. Run scan vault command again.
4. In my case, the command is always stuck with an excalidraw file, as shown in screenshot. ( My guess is that the file size is too large.)
5. Remove the problematic file.

![image](https://user-images.githubusercontent.com/56729449/223331375-8e4a0ec1-3648-4a28-b972-6f096982f17f.png)

**Comment by OtakuAltair** [comment]
It doesn't seem to like numbers or non english characters like japanese. That's hampering my note-taking alot...

**Comment by whitewatercn** [comment]
> It doesn't seem to like numbers or non english characters like japanese. That's hampering my note-taking alot...
> 
> Is there a way to blacklist folders? That would be very helpful for this

i am using chinese mainly, and the solution of delete large file really solve it, maybe you can seperate your large file to some small files

**Comment by ShootingKing-AM** [comment]
Thanks for the information.
