### ISSUE TITLE
Cannot run script

### ISSUE THREAD

**Issue by tallguyjenks** [Pseudonium/Obsidian_to_Anki#42]
MacOS Catalina latest version
zsh
latest verson of script
gooey installed
get this output:

```bash
2020-09-14 00:19:35.492 Python[96244:9342388] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-09-14 00:19:35.492 Python[96244:9342388] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
```

everything was set to defaults, script in in directory with 1 file, that one file has default syntax from repo readme:

```
TARGET DECK
Default

{Begin Note}
Basic
This is a test.
Back: Test successful!
{End Note}

{Begin Inline Note} [Basic] This is a test. Back: Test successful! {End Inline Note}  
```

nothing was converted into Anki besides the deck if it didn't exist, but they always stay empty

**Comment by Pseudonium** [comment]
Hmm. This looks like a problem with Gooey potentially - might want to raise an issue there.
The newest update only adds GUI and an easycloze feature, so you should be fine using the version immediately before for the time being.

**Comment by tallguyjenks** [comment]
will attempt prior version!

**Comment by tallguyjenks** [comment]
i went as far back at 1.0 man, i don't get any errors but no cards are being put in where they were before on my system. i haven't changed anything that should affect this

**Comment by Pseudonium** [comment]
Ah wait I just took a look at the file you did...

Dang, I really need to change that documentation. The curly brackets are meant to communicate substitution - so, you put "START" in place of "{Begin Note Line}", and "END" in place of "{End Note Line}" etc. My bad.

**Comment by tallguyjenks** [comment]
:) let me test again

**Comment by tallguyjenks** [comment]
im good with 2.1.0 images and all 👍🏻

**Comment by Pseudonium** [comment]
Ah great! I'll see if I can find your problem on the existing issues for Gooey, if not I'll let them know.

**Comment by Pseudonium** [comment]
https://github.com/chriskiehl/GooeyExamples Could you take a look at some of those and see if they run?

**Comment by tallguyjenks** [comment]
well, the window came up. you know I'm wondering if the error was just the original syntax I was using from the readme and not gooey let me see.

**Comment by Pseudonium** [comment]
Hmm, ok. Another user was having some problems with the config file, and I fixed it by altering the encoding slightly - that might've been related? Try redownloading latest script version (maybe put it in a different directory just for testing) and see if that works.

**Comment by tallguyjenks** [comment]
Yeah just tried it, fresh and everything, I get the same error. The gui window pops up but I get the same error text in my terminal now

**Comment by Pseudonium** [comment]
Weird. The examples work fine, but my script fails.

**Comment by tallguyjenks** [comment]
🤷‍♂️️

**Comment by Pseudonium** [comment]
What's your Python version? Currently making an issue on Gooey to see what could be causing this

**Comment by tallguyjenks** [comment]
3.8.5

**Comment by Pseudonium** [comment]
Latest version of the script (v2.4.0) allows you to disable the GUI from the config file, falling back to the old command-line functionality. You should be good to go for now, as we attempt to fix the Gooey issue. Let me know if the script still breaks though - that'll mean the issue isn't with Gooey, but something else I've changed.

**Comment by Pseudonium** [comment]
The next update of the script will have it fall back to a command-line interface if it detects Gooey is not installed, so you should be able to access all features from them on.
