### ISSUE TITLE
[Sharing] A stricter cloze regex

### ISSUE THREAD

**Issue by Ali-C-Ila** [Pseudonium/Obsidian_to_Anki#425]
## background knowledge
https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Cloze-Paragraph-style
(Curlycloze also seems to have zero funtion for me, see #377 )

## feature
The officially provided regex for cloze will recognize any "{", which could be really annoying when using {{templates}}, Excalidraw, etc.

So I modified this version, which only recognizes a full cloze format( with double colons) such as {{c1::text}}.

Disclaimer: This is a work of AI. I have no idea how to write regex myself, so test in a sandbox and backup your data before using this!
```regex
((?:.+\n)*(?:.*\{\{[^\{\}]*::[^\{\}]*\}\}.*)(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)
```

## positive and negative examples
![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/56729449/3fff7ab6-390e-47b6-8b3d-8d39e27b75d8)

![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/56729449/fa02ef0b-dee4-4c66-94ee-4c7c940b8c76)

**Comment by lsolesen** [comment]
@Ali-C-Ila This has worked well for me. However, when using Obsidian_to_Anki it goes very slow when parsing Excalidraw-drawings. I am not certain that this regex is at fault, just wanted to know whether you have any experience with that?

**Comment by niposch** [comment]
related #288 and #289
