### ISSUE TITLE
(Feature Request) Scan Document instead of Scan Vault

### ISSUE THREAD

**Issue by lord-hieros** [Pseudonium/Obsidian_to_Anki#430]
**Feature Request**

Add an option to scan current document instead of the whole vault. This would help with some of the memory issues and also make it easier to work on flash cards in another document before you sync if they’re not ready.

**Comment by Bai2035** [comment]
Need it. When I learn in Anki I will change the content, but scan the vault may change it back.

**Comment by ShootingKing-AM** [comment]
same as #390
