### ISSUE TITLE
Cant seem to get regex working correctly

### ISSUE THREAD

**Issue by mesa123123** [Pseudonium/Obsidian_to_Anki#437]
I'm trying to write flashcards in obsidian that use the format:

Q: {front of card}
A: """ {back of card} """

But this would also be valid:

Q: {front of card}
A: """
{back of card}
"""

or:

Q: {Front of card}
A: """
{back of card}"""

How would I go about doing this?
I've tried to build the regex using multiple helper website but as much I as get them correct they don't seem to translate well to the plugin itself, is there a nuance I'm not picking up on?

Could someone please help??

**Comment by mesa123123** [comment]
Currently using:
^Q: ((?:.+\n)*)\n*A: """((.*?)|(\n*?)*)"""

But thats defintiely not working,

I've also tried many variations on the one used here:

^Q: ((?:.+\n)*)\n*A: (.+(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)

Please help!

**Comment by guillaume-troadec** [comment]
This should do what you want :)

`Q: \{(.*)\}\nA: """\s*\n*\{(.*?)\}\s*\n*"""`

Good luck

![Screen Shot 2023-10-15 at 10 20 07 pm](https://github.com/Pseudonium/Obsidian_to_Anki/assets/35596490/4c215b01-c73e-4e48-87f7-8aee417582ef)
