### ISSUE TITLE
Could not create Neuracache flashcard with tags

### ISSUE THREAD

**Issue by DelmarHuang** [Pseudonium/Obsidian_to_Anki#440]
Hi, thank you a million for this wonderful plugin. I wonder how to interpret tags in Obsidian note by creating a Neuracache flashcard

So I have turn on "Add Obsidian Tags", and take my note as follows:

```
do a multi-line question #flashcard
You just need to make sure both
the question and answer are one paragraph. #products 
Tags: products 
```

So there are two styles of tags, one by #, another by Tags:

But both don't work in Anki. They are still in the note instead of a tag.

Could you please kindly instruct how to do it? Thank you very much

**Comment by flavioipiranga** [comment]
Hi @DelmarHuang,

I tried to reproduce your example:
![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/5366162/8313f27a-603c-4438-a88b-b1c75526cd9d)

I used the following obsidian note:
```
START
Basic
do a multi-line question #flashcard
You just need to make sure both
the question and answer are one paragraph. #products
Tags: products
END
```

Could you check if using the above text works in your environment?

**Comment by flavioipiranga** [comment]
Hi @DelmarHuang,

Looks like this is handled here: #230
