### ISSUE TITLE
Unclear Documentation for Neuracache

### ISSUE THREAD

**Issue by not-alaris** [Pseudonium/Obsidian_to_Anki#441]
It may be somewhere else, and I just don't understand, but I was wondering why I couldn't find a way to create reversed cards while using the Neuracache custom regex. I'm referring to the native ability of Anki to create different types of cards. It's unclear to me, however it may be hidden in the wiki somewhere, but I'm unable to find it. If anyone is able to assist me, i'd appreciate it.

**Comment by niposch** [comment]
Reverse cards is an anki note type, right? It should be possible to configure which regex is used for which note type from the settings:
![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/45246069/8c292069-5a48-4fc9-af4d-c932950116bb)
and then you can configure custom note types you created in anki in there:
![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/45246069/888d14ba-cbd3-415c-8615-d432c9cbda47)

So you can set the normal #flashcard regex for the normal Note type and then modify the regex by replacing "flashcard" with "reverse" if you want to create a reverse flashcard using #reverse tag.
For this to work you'd need to create new Note type that shows the answer field on the front and the question on the back.
https://docs.ankiweb.net/editing.html#adding-a-note-type
