### ISSUE TITLE
Anki does not detect the cloze formatting

### ISSUE THREAD

**Issue by MasterSmalll** [Pseudonium/Obsidian_to_Anki#453]
Hello everyone,

I'm trying to import cloze flaschards into Anki with the cloze formatting syntax. 
The export from Obsidian to Anki works, but once in Anki the fields filled in are not detected and the software tells me that the map is empty. 
The flashcard was imported as in Obsidian with {cloze} a#nd not transformed in Anki with {{c1::cloze}}. 

For your information, I did activate "CulryCloze" in the settings. 

Thanks for your help.

**Comment by niposch** [comment]
It'd be helpful if you can provide an example with which you're having problems.
I tried it and it works for me. Maybe double-check your settings and compare them to mine.
My markdown:


```markdown
Test {cloze}
even with multiple {lines}
```

the result:
![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/45246069/3f718fe3-c2b8-4689-91d8-e75dbefffbfe)


# my settings

![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/45246069/9cbc9134-4340-4dd2-b6be-cd48c64a1d06)


![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/45246069/42f51ab2-ef4e-473f-9a9d-56dfde4e8874)
## note type settings
![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/45246069/0284b995-e655-4314-b43b-ee4712e44f67)
(second dropdown is set to text aswell)
the regex got it from [here](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Cloze-Paragraph-style):
```regex
((?:.+\n)*(?:.*{.*)(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)
```

**Comment by MasterSmalll** [comment]
First of all, thank you for your reply, but it still doesn't work. 

The plugin settings are similar to yours. 

![Plugin](https://github.com/Pseudonium/Obsidian_to_Anki/assets/149117033/af27771a-80bb-4976-aab2-37b83467918c)

I've got the same regex as you and the card type is set to "cloze" in the table type note. 
![Plugin](https://github.com/Pseudonium/Obsidian_to_Anki/assets/149117033/edf6cf3e-098e-4b95-bafc-448ac4bcde6a)

The problem is still the same, the export is carried out correctly in Anki by creating a unique ID in Obsidian, the map is displayed in Anki but the cloze deletion format remains unchanged. 


![Plugin](https://github.com/Pseudonium/Obsidian_to_Anki/assets/149117033/f595fa96-2734-49d0-a3ca-5d839887e655)
I've just completed the import by scanning the vault. 

This is how it appears in Anki, and when I study the map, I get this error message (in French because I speak French). 
![Plugin](https://github.com/Pseudonium/Obsidian_to_Anki/assets/149117033/0cd998b9-b573-4d03-b0fd-ec4009adfded)
![Plugin](https://github.com/Pseudonium/Obsidian_to_Anki/assets/149117033/80e0923b-d86e-4187-b0bb-c2b351525f59)

On the console side, there are no error messages.

**Comment by niposch** [comment]
afaik the curly cloze option only works on note types where the note type name contiains "cloze". Yours is "textes à trous" so maybe this breaks it. It may be worth to rename this in anki to something with cloze in the name and  then press this in the settings:
![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/45246069/f4cb79d3-eab3-4527-8581-2d2c3194bf07)

**Comment by niposch** [comment]
@MasterSmalll 
Checked the code today, and it looks like the deck name has to contain the word "Cloze" with the first letter capitalized.

**Comment by MasterSmalll** [comment]
Thanks for your help @niposch, it was in fact a syntax problem, now it works.

**Comment by zeitchef** [comment]
@niposch Can you describe the syntax issue you were facing? I'm seeing the same behavior.
