### ISSUE TITLE
Excluding some file types

### ISSUE THREAD

**Issue by Abod1960** [Pseudonium/Obsidian_to_Anki#466]
So I use excalidraw plugin, and when ever I run the obsidian to anki plugin it lags there on the .excalidraw files, so I was wondering if I can prompt obsidian to anki plugin to no scan those files...

Just wanted to say I am very thankful for this plugin, I am a med student and I have exams within few days and what is getting me through this situation is this plugin, so thank you very much to creator and the community and the maintenance guys working in the plugin...

**Comment by serpro69** [comment]
If you have your anki cards in a separate directory - you can set a specific directory (instead of the whole vault) to scan via settings, thus excluding everything else that is outside of that dir

**Comment by Abod1960** [comment]
> If you have your anki cards in a separate directory - you can set a specific directory (instead of the whole vault) to scan via settings, thus excluding everything else that is outside of that dir

I looked at the settings and wasn't able to see any setting associated with assigning a specific directory, can u send me a screenshot of where it is, I will be thankful...

**Comment by serpro69** [comment]
![image](https://github.com/Pseudonium/Obsidian_to_Anki/assets/22973227/18ed960a-37f6-4780-9bad-67752a173b03)

Make sure you're on latest version.

**Comment by ShootingKing-AM** [comment]
This is also related to https://github.com/Pseudonium/Obsidian_to_Anki/pull/289
