### ISSUE TITLE
How to run Obsidian_to_Anki without GUI?

### ISSUE THREAD

**Issue by ddfonseca** [Pseudonium/Obsidian_to_Anki#47]
Hi, I'm having trouble installing Goeey from my machine (Manjaro Linux, up to date). It seems that for[ Linux distributions ](https://stackoverflow.com/questions/38820550/python-installing-gooey-using-pip-error)it is harder install Gooey. It says to install for python2 but your script is for python3, which doesn't make any sense.

So, how to run just in command line like earlier versions?

Thanks

Edit: Because if I try to run give me "Gooey" is not installed:
```
> python3 obsidian_to_anki.py
Traceback (most recent call last):
  File "obsidian_to_anki.py", line 12, in <module>
    import gooey
ModuleNotFoundError: No module named 'gooey'
```

**Comment by Pseudonium** [comment]
Hmm, and I'm assuming `pip install gooey` doesn't work, right?

**Comment by ddfonseca** [comment]
> Hmm, and I'm assuming `pip install gooey` doesn't work, right?

Yeah, give me a lot of errors

**Comment by Pseudonium** [comment]
Have you tried the `git clone` command they suggested?

**Comment by Pseudonium** [comment]
If you're still having problems, version 2.1.0 is the latest version without the Gooey dependency.

**Comment by ddfonseca** [comment]
> Have you tried the `git clone` command they suggested?

I'll try here before ask any dumb question


> If you're still having problems, version 2.1.0 is the latest version without the Gooey dependency.

I see, but I'd like the CurlyCloze feature that is on 2.2.0 :(

**Comment by Pseudonium** [comment]
Next release should fix this for you - if the script detects that gooey isn't installed, it'll fall back to the command-line interface.

**Comment by ddfonseca** [comment]
Thank you very much!! Now I can use the program without problems! 👍👍

**Comment by Pseudonium** [comment]
No problem! Just to check, what worked? Did the `git clone` for Gooey work, or are you just not using Gooey and instead using the command-line interface?

**Comment by Pseudonium** [comment]
Ah no problem! I’m currently working on allowing you to run the script recursively (so you can run it on your top-level notes folder and it’ll do all the notes in all subfolders), which should make it even easier to use!

I’m also investigating adding functionality that lets you schedule the script to run at a certain time every day, but I think this may already be possible with some external scripting. Do you think it’d be useful to have it inbuilt?

**Comment by ddfonseca** [comment]
Yeah, absolutely! The first one will be really nice! At the moment, I have few notes to add to Anki, so it isn't a problem, but I like the idea!

The second one is not quite necessarily useful, because it need Anki to be open to run the script, so I don't know if it's nice to have Anki open all the times... If I want the card, just run the script!

(I am slow to write because it's not my first language)

**Comment by Pseudonium** [comment]
Good point - the script requires Anki to be open to work, since that’s how AnkiConnect functions. So you would have to have Anki open always. I’d have to rewrite many things in order to have the script work even if Anki was offline. I’ll probably not do that then. But I’ll keep working on the recursive feature. Thanks for your input!

**Comment by ddfonseca** [comment]
That's right. You're welcome! :+1:

**Comment by Pseudonium** [comment]
By the way, I’ve now implemented the recursive feature. Also, if you supply the path to the Anki executable and the name of your profile, the script will automatically open Anki when run if it isn’t already running! So, you can automate it to e.g. run every day more easily.

**Comment by ddfonseca** [comment]
Thank you! That's awesome!
