### ISSUE TITLE
Same sentence for each card (on Field)

### ISSUE THREAD

**Issue by ddfonseca** [Pseudonium/Obsidian_to_Anki#50]
Hi again, this is not an issue, but I don't know where to request a feature 🤷‍♂️

I would like to have a fixed field like that of FILE TAGS for all cards from .md file. One of the best plugins that I use on Anki is Frozen Fields, but how this can be done on Obsidian_to_Anki? It will make files more cleaner.
Example, if I have a custom card with 3 fields: Context (C:), Question (Q:), Answer (A:):

```
C: What is the country's capital?

Q: USA?
A: Washington, DC.

Q: Brazil?
A: Brasilia
```
Is it possible to repeat the same C: for every card? 

Thanks

**Comment by Pseudonium** [comment]
This would be a little challenging to implement, but not impossible. For my future reference, here's how I'd implement it:
* New section in config file - Custom Frozen Regexps
* For each note type, you can define a frozen regexp
* When generating a note, it'll take anything in the first frozen regexp match for that note type, and add it as another field
* It's fine to give less than the required number of fields to AnkiConnect, or fields with the wrong names, so don't worry about that

Not sure when I'd be able to implement this however - currently busy with the recursive functionality as you know.

**Comment by ddfonseca** [comment]
OK thank you! No need to rush, the script is already functional as it is! I would like to thank you again, because the combination of Obsidian and Anki is phenomenal. Thanks

**Comment by dummifiedme** [comment]
+1 to this thing. One frozen context field can hugely help :)

**Comment by Pseudonium** [comment]
Alright, idea for how this could work, with as little clutter to the config file as possible:

Add a FROZEN syntax (the actual word FROZEN can be changed in config file), which works by placing this block somewhere in your file:

```
FROZEN - {Note type}:
{Field 1}: {Content 1}
{Field 2}: {Content 2}
...

```

As an example, if your note type was called "Question with context":

```
FROZEN - Question with context:
Context: What is the country's capital?

```

That adds only one thing to the config file (changing what FROZEN can be), and is a pretty simple solution too. I'll see if I can implement this.

**Comment by Pseudonium** [comment]
@ddfonseca Yep, have managed to implement this in my latest commit! Works with multiple "FROZEN" blocks corresponding to different note types as well. It'll append anything in the 'frozen' note to any other note with the associated note type - works for regex notes too. You should hopefully see this soon!

**Comment by Pseudonium** [comment]
@ddfonseca Yep, have managed to implement this in my latest commit! Works with multiple "FROZEN" blocks corresponding to different note types as well. It'll append anything in the 'frozen' note to any other note with the associated note type - works for regex notes too. You should hopefully see this soon!

**Comment by dummifiedme** [comment]
So the if I have my REGEX note type with 3 fields, Q, A, and context 

how will It make the frozen content to go for Context field?
