### ISSUE TITLE
Did not recognise note type  Basic

### ISSUE THREAD

**Issue by jlxfd** [Pseudonium/Obsidian_to_Anki#510]
I checked and Anki's language in preferences is in English. Here is the error that I'm getting:
<img width="381" alt="image" src="https://github.com/Pseudonium/Obsidian_to_Anki/assets/114143577/981eaafe-7b2a-4dcf-ae55-4803afb6ffc0">
And here is the basic card that I'm making:
<img width="325" alt="image" src="https://github.com/Pseudonium/Obsidian_to_Anki/assets/114143577/3c9c161e-abd1-426e-a726-3564817b3042">

**Comment by ShootingKing-AM** [comment]
Do add your solution here, if possible, so that others can find if they face the same problem.

**Comment by flapjack89** [comment]
Hi. What was the solution? I see the same error message with a custome note type

**Comment by CraftOldWang** [comment]
Hi.I think there was a note type "Basic" but now it has been removed.So 
I met the same problem and then I try to use the regex from others and use their format.It works.
![image](https://github.com/ObsidianToAnki/Obsidian_to_Anki/assets/144406313/e0a9de97-0afd-4217-9d81-71a15d504608)

Specifically,I use the regex from him. 
https://www.bilibili.com/video/BV1Ai4y1p7Bb/?vd_source=a6856e18e3c3a6ab4189065dd294d5a6
you can copy the regex from the comments,but you should replace【】with[],like this
((?:[^\n][\n]?)+\n)-{4,}((?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)

and his format is

##the front
----
the back


It seems that you should put the regex in right note type,for different type correspond to different type of cards in Anki.
 Just then I put the regex in "填空题",which means cloze (maybe),it can be exported to Anki successfully but can't be displayed correctly.So I put it into "问答题",which means Q&A,it works.
