### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by EngineerLeonJ** [Pseudonium/Obsidian_to_Anki#54]
### Error Message:
Attempting to connect to Anki...
Connected!
Loading configuration file...
Loaded successfully!
Identified target deck for .\202009152153 1K411011 城镇道路分类与分级.md as Default
Identified target deck for .\202009152220 城镇道路分级.md as Default
Identified target deck for .\202009152221 柔性路面的破坏取决于.md as Default
Identified target deck for .\202009152223 刚性路面的破坏取决于.md as Default
Scanning file .\202009152153 1K411011 城镇道路分类与分级.md  for notes...
Scanning file .\202009152220 城镇道路分级.md  for notes...
Scanning file .\202009152221 柔性路面的破坏取决于.md  for notes...
Scanning file .\202009152223 刚性路面的破坏取决于.md  for notes...
Getting tag list
Adding media with these filenames...
[]
Adding directory requests...
Forming request 1 for directory E:\_Nutstore\我的坚果云\_2020OBLibrary\《1K400000 市政公用工程管理与实务》\1K410000 市政公用技术\1K411000 城镇道路工程\1K411010 城镇道路工程结构与材料\1K411011 城镇道路分类与分级
Adding notes into Anki...
Updating fields of existing notes...
Getting card IDs of notes to be edited...
Removing empty notes...
Traceback (most recent call last):
  File "E:\_Nutstore\我的坚果云\_2020OBLibrary\Obsidian_to_Anki-master\obsidian_to_anki.py", line 1493, in <module>
    main()
  File "E:\_Nutstore\我的坚果云\_2020OBLibrary\Obsidian_to_Anki-master\obsidian_to_anki.py", line 183, in main
    App()
  File "E:\_Nutstore\我的坚果云\_2020OBLibrary\Obsidian_to_Anki-master\obsidian_to_anki.py", line 868, in __init__
    directory.parse_requests_1(AnkiConnect.parse(response), tags)
  File "E:\_Nutstore\我的坚果云\_2020OBLibrary\Obsidian_to_Anki-master\obsidian_to_anki.py", line 1432, in parse_requests_1
    file.card_ids = AnkiConnect.parse(card_ids)
  File "E:\_Nutstore\我的坚果云\_2020OBLibrary\Obsidian_to_Anki-master\obsidian_to_anki.py", line 211, in parse
    raise Exception(response['error'])
Exception
### Attachments
[Script & MD Files.zip](https://github.com/Pseudonium/Obsidian_to_Anki/files/5249361/Script.MD.Files.zip)

**Comment by Pseudonium** [comment]
So this is an error with AnkiConnect getting the card IDs. How have you used the script before, by the way?

**Comment by Pseudonium** [comment]
A potential fix is - delete all the cards created by the script from Anki, and also remove all the ID lines. Let the script re-add to Anki.

**Comment by Pseudonium** [comment]
And I've just tested - it shouldn't be an issue of the script reading IDs incorrectly. It should be able to read both old format and new format IDs perfectly fine.

Let me know what works.

**Comment by EngineerLeonJ** [comment]
I have tried to delete all the cards created by the scipt from Anki, but nor sure how to remove all the ID lines; The tags have been removed also. 
For Ankiconnect, this is the config file:
{
    "apiKey": null,
    "apiLogPath": null,
    "webBindAddress": "127.0.0.1",
    "webBindPort": 8765,
    "webCorsOrigin": "http://localhost",
    "webCorsOriginList": [
        "http://localhost"
    ]
}
Maybe the following issues affect:
1. I am using AnkiTab Extension at the same time;
2. the folder name includes special characters, including space ,'《》'and chinese words
3.Before I have use polar bookshelf which also write something into Anki

**Comment by Pseudonium** [comment]
Ah, you’d have to manually remove the ID lines. A find/replace tool might help.

I don’t think those should affect it, but try turning them off anyway.

**Comment by Pseudonium** [comment]
Just thought of one thing - have you ever deleted a card in Anki added by the script, but not removed the ID line in the file? That’d cause this error, as the script attempts to get info on a note that no longer exists.

**Comment by EngineerLeonJ** [comment]
yes i think this is the reason, kindly close this issue, after work finish i will try to delete the ID line tonight
thank u

**Comment by Pseudonium** [comment]
Ah great! I’ll add a warning on deleting notes in the documentation - once that’s done, I’ll close thus issue.

**Comment by EngineerLeonJ** [comment]
Confirmed for the reason that deleting notes without deleting the ID line. I have tried for other md files and it works well. However, I don't know how to delete, hope this will be updated in the GUI.
(I have read https://github.com/Pseudonium/Obsidian_to_Anki#deleting-inline-notes but still failed)
