### ISSUE TITLE
File versioning

### ISSUE THREAD

**Issue by BrayanDSO** [Pseudonium/Obsidian_to_Anki#56]
Whenever I run the script in a directory, it changes the 'last modified' date even if the file hadn't any cards.
It's okay to modify the files with cards to add the scripts, but I don't think this should happen with the files without cards.

**Comment by Pseudonium** [comment]
Ah yes, I can see why that would happen. I’ll do a fix so that it won’t write to the file if nothing has change.

**Comment by Pseudonium** [comment]
Fixed in v2.8.0. Thanks for bringing this to my attention, you've improved the experience for future users!
