### ISSUE TITLE
When processing markup files from a directory use natural order.

### ISSUE THREAD

**Issue by twisp007** [Pseudonium/Obsidian_to_Anki#59]
Currently the markup files are processed randomly. The problem with this approach is the order in which cards are inserted into anki is the order in which they are reviewed. If someone wants a certain order (study material progresses through chapters...) that is a problem.

I request at least for an option that process markup files in order that humans call natural.

Now:

```
1.txt
9.txt
7.txt
2.txt
```

Requested:

```
1.txt
2.txt
7.txt
9.txt
```

**Comment by Pseudonium** [comment]
Ah yes. Python's function for scanning a directory returns the files in an arbitrary order, and I can see why that would be a problem. Shouldn't be too difficult to fix - I can just sort the list of files once it's made. Good idea!

**Comment by Pseudonium** [comment]
Fixed in v2.8.1
