### ISSUE TITLE
Reverse cards #flashcard-reverse

### ISSUE THREAD

**Issue by Mike-Ki** [Pseudonium/Obsidian_to_Anki#594]
I think it would be cool if one could create two anki cards by adding the tag #flashcard-reverse.

**Comment by johamada** [comment]
Isn't it something you can do easily by using the Card-type in Anki (https://docs.ankiweb.net/templates/generation.html#reverse-cards) together with custom regex?

**Comment by Mike-Ki** [comment]
That's cool! Thank you very much for the tip :)
