### ISSUE TITLE
Parsing incorrectly

### ISSUE THREAD

**Issue by BrayanDSO** [Pseudonium/Obsidian_to_Anki#61]
I'm using the Header Paragraph style (Level 4+)
If I try to make a question like this:
```
#### My question
Answer
- a
- b
- c
```
The result doesn't parse the list correctly:
![200921135016](https://user-images.githubusercontent.com/69634269/93796854-ccde8480-fc11-11ea-911b-cd8b9b52edf6.png)

Without the text before the unordered list, it works fine:
![image](https://user-images.githubusercontent.com/69634269/93797116-3199df00-fc12-11ea-8a16-8602f54f609f.png)

**Comment by Pseudonium** [comment]
This is a limitation of the [sane list](https://python-markdown.github.io/extensions/sane_lists/) extension - you do need the newline. If I removed it, you'd instead get unexpected behaviour with mixing list items. Not really something I can fix unfortunately.

**Comment by Pseudonium** [comment]
I’ll add a note about this on the documentation.

**Comment by BrayanDSO** [comment]
Alright. I don't think this is much of a problem because the list with the "-" is fine. 
Just wanted to know if it was an error or something else.

**Comment by BrayanDSO** [comment]
Is there some way to disable the parsing for all lists, so it stays equal in my notes?

**Comment by Pseudonium** [comment]
Hmm, I might be able to add something to the config file to allow you to specify what extensions to use.

**Comment by BrayanDSO** [comment]
It would be nice. This would make the script even more powerful.
Feel free to close the issue if you want

**Comment by Pseudonium** [comment]
Yeah, have now decided against adding anything else to the config file! Really want to minimise bloat. So I'll close this issue.
