### ISSUE TITLE
Allow multiple tags in the same file.

### ISSUE THREAD

**Issue by twisp007** [Pseudonium/Obsidian_to_Anki#63]
I ended up generating 6k+ text files for 6k+ cards (1:1).

It is because a text file can contain only one set of tags: `File Tags Line - The string that signals "the line beneath me is the set of tags that should be added to all notes from this file". Defaults to FILE TAGS.`. Otherwise only ~300 text files needed to be generated. 

Please improve upon the syntax so the tags apply to a set of cards in the same file.
Eg:

```
TARGET DECK
DECK1
FILE TAGS
tag1 tag2
START
note-1
val1
f2: val2
END
FILE TAGS
tag1 tag3
START
note-2
val3
f2: val4
END
START
note-2
val5
f2: val6
END
```

Also the script kind of stopped for a long time* at `Replacing tags...`. I wonder if it is due to the huge number of files. 

It is still running for almost an hour. Started at 00:13 and now it is 00:55. (I can't exactly tell when it stopped but it stopped before 01:01)

**Comment by Pseudonium** [comment]
Wow, that’s a huge number of files!
What about specifying the tags for each note, by doing Tags: {tag list} just before END? That seems like it’d allow you to compact things into fewer files.
I haven’t tested the script with that many files, but it makes sense that it’s taking so long - I don’t think there’s any performance improvement I can do on my end though, since all the Anki modification is done via AnkiConnect.

**Comment by Pseudonium** [comment]
Indeed, if you’re automatically generating so many cards, it’d probably be simpler/faster to just use Anki’s default import from an excel table or csv file.

**Comment by twisp007** [comment]
The problem with using Anki default import is it doesn't allow different note types and decks. If not for the tags issue this program is exactly what I need.

**Comment by Pseudonium** [comment]
What about specifying tags for each note then? Or generating a separate file for each note type? I’m assuming you don’t have a huge number of different note types.

**Comment by twisp007** [comment]
> What about specifying the tags for each note, by doing Tags: {tag list} just before END?
> What about specifying tags for each note then? 
Specifying tags for each note at the end will totally work for me.

> Or generating a separate file for each note type? I’m assuming you don’t have a huge number of different note types.

The issue with grouping based on note types is it will mess the order in which they are supposed to be inserted into Anki (and thus reviewed).

**Comment by Pseudonium** [comment]
Ok, since specifying tags at the end should work I’ll mark this as closed.
