### ISSUE TITLE
Allow naming the 1st field also.

### ISSUE THREAD

**Issue by twisp007** [Pseudonium/Obsidian_to_Anki#64]
The first field named doesn't have to be mentioned. Which I can see as an advantage when manually creating the markdown files but when generating markdown files using scripts it's a little harder. If **optionally** naming the first field is allowed then the fields and the values can be generated in any order and this in turn makes the scripting much easier.

**Comment by Pseudonium** [comment]
Well, the fields do actually need to be in the same order in the file as in Anki - arbitrary order doesn’t work.

It might be simpler to use a regexp when bulk-generating notes, rather than the default syntax?

**Comment by Pseudonium** [comment]
Or, as I mentioned in #63, just use Anki’s default import from a csv file/excel table.

**Comment by twisp007** [comment]
> It might be simpler to use a regexp when bulk-generating notes, rather than the default syntax?

I will look into this.

> just use Anki’s default import from a csv file/excel table.

Repeating #63, Anki doesn't allow multiple decks and note types in a single import file.

**Comment by Pseudonium** [comment]
In any case, I’m not planning on implementing new functionality or modifying existing functionality at the moment, unless it’s an actual bug.

**Comment by Pseudonium** [comment]
As a note, when using custom regexps, it’ll add notes in clumps of note types, rather than the absolute order in the file. It’ll also ignore any START END formatted notes.
