### ISSUE TITLE
Obsidian link doesn't work

### ISSUE THREAD

**Issue by ddfonseca** [Pseudonium/Obsidian_to_Anki#65]
Hi, I don't If I'm doing this correctly, so in my config I put this:

```
[Obsidian]
Vault name = Obsidian
Add file link = True
```
Obsidian is the name of my Vault on $HOME/Documents/, should I put the whole path?

Then it creates a link on Anki, but I couldn't open it:

![image](https://user-images.githubusercontent.com/9698814/94004472-23170900-fd73-11ea-8ed0-a25b1a71cd91.png)

Another question, is it possible to add an ID on this link that we could change the CSS style from the cards (not important, by the way)? But a linebreak before insert it would be nice too.

Thanks

**Comment by Pseudonium** [comment]
Hmm, have you tried the Obsidian url scheme outside of this script, just typing e.g. `obsidian://vault/Obsidian`?

**Comment by ddfonseca** [comment]
> Hmm, have you tried the Obsidian url scheme outside of this script, just typing e.g. `obsidian://vault/Obsidian`?

Where should I type this? On firefox just enter on Google, on my File Manager give me an error

**Comment by Pseudonium** [comment]
Yeah just type it in a web browser.

**Comment by ddfonseca** [comment]
> Yeah just type it in a web browser.

I tried both on Firefox and Chrome and go directly to Google search

**Comment by Pseudonium** [comment]
Hmm, that seems to be an issue with the irl scheme itself. Are you on Linux by any chance?

Might want to ask for help in the discord, or file a bug report.

**Comment by Pseudonium** [comment]
![image](https://user-images.githubusercontent.com/27702145/94011191-ee20ab80-fd9e-11ea-83f4-9e1df3a264e6.png)

That's the pop-up you should get when typing in Chrome.

**Comment by Pseudonium** [comment]
Even if I just type `obsidian://`, that pops up for me (despite not being a valid URL). So, if you're not getting that popup, then it's an issue with the URL scheme not working on your device.

The URL scheme is an Obsidian 0.8.15 feature - have you upgraded to the latest version?

**Comment by ddfonseca** [comment]
Ok!! I still can't open, but it is definitely no longer a bug on obsidian_to_Anki! Thanks for the support

**Comment by Pseudonium** [comment]
Ok then! I’ll close this issue for now, but by all means reopen it if you get the urls working but the script urls still fail.

**Comment by Pseudonium** [comment]
By the way, a question for the next time I update the script (maybe around when 0.9.0 releases publicly) - would it be enough to add a custom class to the Obsidian link for the css styling? I’m not that familiar with css myself, so I’m wondering what a user would want.

The new line makes sense, so I’ll also change it to be a new line rather than a space when I next update.

**Comment by ddfonseca** [comment]
Yes! It would be enough to add a custom class or custom id to the Obsidian link. That's because the Obsidian link is distracting me a little bit, but with a custom css I could make the link smaller and grey, without drawing too much attention.

 At the moment, because I don't have too many links on my cards, I'm changing all the ahref tag to make this effect, but I just want to add that particular css style on the Obsidian link not for all ahref tags.

**Comment by ddfonseca** [comment]
> The new line makes sense, so I’ll also change it to be a new line rather than a space when I next update.

Thanks!!

**Comment by Pseudonium** [comment]
@ddfonseca Oh, forgot to say but this has changed in the latest version of the script! Links are now a newline by default, and have the class "obsidian-link".

**Comment by ddfonseca** [comment]
> @ddfonseca Oh, forgot to say but this has changed in the latest version of the script! Links are now a newline by default, and have the class "obsidian-link".

Thank you Pseudonium! The last 3 months I haven't checked GitHub but I am using Obsidian_to_Anki daily! I really appreciate all the effort you put in this script/add on! Thank you!
