### ISSUE TITLE
FILE TAGS inline

### ISSUE THREAD

**Issue by BrayanDSO** [Pseudonium/Obsidian_to_Anki#66]
Instead of the default behavior which uses 2 lines
```
FILE TAGS
Math Physics
```

Is there a way to put the File Tags in just one line? like this
```
FILE TAGS: Math Physics
```

**Comment by Pseudonium** [comment]
Nope, it has to be 2 lines. I can allow you to format it like the second line if you want - it's a one-line change in the code.

**Comment by BrayanDSO** [comment]
It would be nice to have this as an option in the configs

Em qua, 23 de set de 2020 11:14, Pseudonium <notifications@github.com>
escreveu:

**Comment by Pseudonium** [comment]
I don't want to pollute the configs too much with options though. And it's not necessary - it's very easy to support both styles the way I've coded it.

**Comment by BrayanDSO** [comment]
I agree with being better to have less configs, there are already too much.

It's even better being able to do both the syntaxes without changing any
config

>

**Comment by BrayanDSO** [comment]
I suppose the same could be made with 'TARGET DECK'

**Comment by Pseudonium** [comment]
Past me should really have actually done that "one-line change in the code"... I guess I have to figure it out again lol

**Comment by Pseudonium** [comment]
Yep, this is in the latest commit! You should see this soon.
