### ISSUE TITLE
Cannot Recognize Multiple answers to one question

### ISSUE THREAD

**Issue by EngineerLeonJ** [Pseudonium/Obsidian_to_Anki#67]
Cannot recognize mutiple answers to one question:
Original md contents:
![image](https://user-images.githubusercontent.com/50700790/94048548-bb99a180-fde4-11ea-80f5-0d6923c65ae6.png)
Recognize Result:
![image](https://user-images.githubusercontent.com/50700790/94048601-d23ff880-fde4-11ea-9256-c2e31e8a3eb9.png)

[202009160852 1K411012 沥青路面结构组成特点.zip](https://github.com/Pseudonium/Obsidian_to_Anki/files/5269913/202009160852.1K411012.zip)

**Comment by Pseudonium** [comment]
This is expected behaviour - it’ll only read the first paragraph after the header, not the whole section. You either need to remove the newlines, or use a different regexp that does everything after the header (I might be able to make one).

**Comment by ddfonseca** [comment]
You can use <br> between lines to make this effect. 
Example: 
# Title 
Answer <br>
Answer2
--
Result:
Front:Title
Back: Answer

Answer 2

**Comment by EngineerLeonJ** [comment]
Thanks, i insert <br> and remove blank lines, now everything okay
> ```
> You can use <br> between lines to make this effect. 
> Example: 
> # Title 
> Answer <br>
> Answer2
> --
> Result:
> Front:Title
> Back: Answer
> 
> Answer 2
> ```
