### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-7

### ISSUE THREAD

**Issue by ShaunakSA** [Pseudonium/Obsidian_to_Anki#68]
Hi, 

I get the following error in the GUI when attempting to add an Obsidian .md file to Anki. I am attaching the .md file to this issue.

Attempting to connect to Anki...
Connected!
Loading configuration file...
Loaded successfully!
Identified target deck for Vocabulary.md as Default
Scanning file Vocabulary.md  for notes...
Getting tag list
Adding media with these filenames...
[]
Adding directory requests...
Forming request 1 for directory C:\Users\ShaunakAgarkhedkar\OneDrive\Japanese Notes\Obsidian Notes\日本語
Adding notes into Anki...
Updating fields of existing notes...
Getting card IDs of notes to be edited...
Removing empty notes...
Traceback (most recent call last):
  File "obsidian_to_anki.py", line 1561, in <module>
    main()
  File "obsidian_to_anki.py", line 187, in main
    App()
  File "obsidian_to_anki.py", line 913, in __init__
    Config.config.write(configfile)
  File "C:\Users\ShaunakAgarkhedkar\Anaconda3\lib\configparser.py", line 918, in write
    self._sections[section].items(), d)
  File "C:\Users\ShaunakAgarkhedkar\Anaconda3\lib\configparser.py", line 922, in _write_section
    fp.write("[{}]\n".format(section_name))
  File "C:\Users\ShaunakAgarkhedkar\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-7: character maps to <undefined>

Please advise if there's anything I can do to fix this.
Really appreciate your efforts, and thank you for creating this script.

Regards,
Shaunak
[Vocabulary.zip](https://github.com/Pseudonium/Obsidian_to_Anki/files/5286773/Vocabulary.zip)

**Comment by ddfonseca** [comment]
Hi, 

I don't know about that error, but I run your file here and worked. It seems you are using RemNote single-line style, right? 

Did you change the custom regex on obsidian_to_anki_config.ini Basic to Basic = ^(.*[^\n:]{1}):{2}([^\n:]{1}.*)? 
And then on Defaults settings change Regex to Regex = True? 
Your file is on Obsidian Vault?

Finally, if you're using RemNote single-line style, you don't need the START basic syntax, get rid of that (but won't infere by the way).

**Comment by Pseudonium** [comment]
This should be fixed with the latest version!
