### ISSUE TITLE
Documentation Request + QoL Issues with Optional Fields

### ISSUE THREAD

**Issue by gjgress** [Pseudonium/Obsidian_to_Anki#69]
More clarification on how fields should be inputted by default would be really helpful. For example, I was struggling with managing multiple optional fields. E.g., if Field 2, Field 3, Field 4 are optional, then

```
START
Note Type
[Field 1 Content]
Field 3: [Field 3 Content]
END
```

is invalid syntax. Instead, you must write

```
START
Note Type
[Field 1 Content]
Field 2:
Field 3: [Field 3 Content]
END
```

In other words, optional fields can be omitted at the end, but not in-between. Either this should be clarified in the Documentation, or change the default behavior. It should also be clarified that you CANNOT explicitly write

```
START
Note Type
Field 1: [Field 1 Content]
END
```

This becomes problematic if Field 1 is optional-- a note of this form:

```
START
Note Type
Field 1:
Field 2: [Field 2 Content]
END
```

is not possible (maybe by leaving a blank line? This seems unintended, though).

**Comment by okerivy** [comment]
Hope to solve this problem.

- I also have a lot of fields, some fields are optional. 
In some cases it is not needed.

- Hope to fill in anki based on the field name, not in order. 

- It is also hoped that the first field can start with the field name, 
because the field written in front of the actual note may not be the first field.

**Comment by Pseudonium** [comment]
Yes, I should probably update the START END field recognition algorithm to account better for optional fields, and also for fields not in order. If I'm honest, that was just the first thing I came up with - I focused much more heavily on the regex side once v2 came out. Will see what I can do about this!

**Comment by Pseudonium** [comment]
Ok, so been doing some development and I've changed the algorithm to work like this:

- Substitutions are no longer a thing, you've gotta type out the field and note name as it would be in Anki.
- The script starts by assuming you're adding text into the first field
- It scans the line, and checks to see if the start of the line starts with something like "Front:" or "Back:" or in general 'a field name' + ":"
- If it finds that, it changes the field it's adding text into, and strips the first few characters from the line virtually (doesn't affect your document)
- If it doesn't find that, it assumes you're continuing to add text into the current field
- In any case, it adds the remainder of the line into the current field

This takes care of optional fields (just don't include them), and you can mix and match the orders of fields too. You don't even necessarily need text in the first field - that can be made optional! And the first field can start with the field name too now.

This should be coming out in an update soon, hopefully this addresses your problems! Honestly, I can't believe the old algorithm stuck for so long...

**Comment by Pseudonium** [comment]
And just did this for inline notes too!
