### ISSUE TITLE
How to run the script silently in schedule without GUI/confirmation?

### ISSUE THREAD

**Issue by EngineerLeonJ** [Pseudonium/Obsidian_to_Anki#75]
I have follow [how-create-automated-task-using-task-scheduler-windows-10](https://www.windowscentral.com/how-create-automated-task-using-task-scheduler-windows-10) and add the schedule like this:
```
C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py-d C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary -r -R
```
The window will appear and need click to finish the sync:
![](https://leonpic01.oss-accelerate.aliyuncs.com/img/20201011170153.png)
It works well , but if the script can run silently without any GUI/click it will be better.

**Comment by BrayanDSO** [comment]
Go to your config file and set "GUI" to False

**Comment by EngineerLeonJ** [comment]
Hi, I just set 'GUI' to False, and run the script like this：
```
C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py -d C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary -r -R
```
but the new note didn't come to anki

**Comment by BrayanDSO** [comment]
I think you missed to use the python interpreter. If you have python installed in your computer and it is in your PATH, put python before the obsidian_to_anki.py path
```
python C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary\.addon\obsidian_to_anki.py-d C:\Users\Leon\OneDrive\_ApplicationData\ObsdianLibrary -r -R
```
