### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by BrayanDSO** [Pseudonium/Obsidian_to_Anki#76]
This is happening when I try to run the script. I don't know if this is a error from the script or AnkiConnect
```
Traceback (most recent call last):
  File "obsidian_to_anki.py", line 1561, in <module>
    main()
  File "obsidian_to_anki.py", line 187, in main
    App()
  File "obsidian_to_anki.py", line 917, in __init__
    directory.parse_requests_1(AnkiConnect.parse(response), tags)
  File "obsidian_to_anki.py", line 1505, in parse_requests_1
    file.get_cards()
  File "obsidian_to_anki.py", line 1261, in get_cards
    self.cards += info["cards"]
KeyError: 'cards'
```

Sometimes the script doesn't crash, but it stays stuck forever

**Comment by BrayanDSO** [comment]
The script adds the notes, but doesn't add the ID comment at the original text file

**Comment by BrayanDSO** [comment]
> This is happening when I try to run the script. I don't know if this is a error from the script or AnkiConnect
> 
> ```
> Traceback (most recent call last):
>   File "obsidian_to_anki.py", line 1561, in <module>
>     main()
>   File "obsidian_to_anki.py", line 187, in main
>     App()
>   File "obsidian_to_anki.py", line 917, in __init__
>     directory.parse_requests_1(AnkiConnect.parse(response), tags)
>   File "obsidian_to_anki.py", line 1505, in parse_requests_1
>     file.get_cards()
>   File "obsidian_to_anki.py", line 1261, in get_cards
>     self.cards += info["cards"]
> KeyError: 'cards'
> ```
> 
> Sometimes the script doesn't crash, but it stays stuck forever

The stuck forever bug is when I have a huge number of cards in my Anki profile. I have 30k+ cards (not generated from the obsidian_to_anky script) and it keeps stuck "Replacing tags...". I need to manually close the script to stop it.

If I use an Anki profile with few cards, it works fine.

**Comment by BrayanDSO** [comment]
>Traceback (most recent call last):
  File "obsidian_to_anki.py", line 1561, in <module>
    main()
  File "obsidian_to_anki.py", line 187, in main
    App()
  File "obsidian_to_anki.py", line 917, in __init__
    directory.parse_requests_1(AnkiConnect.parse(response), tags)
  File "obsidian_to_anki.py", line 1505, in parse_requests_1
    file.get_cards()
  File "obsidian_to_anki.py", line 1261, in get_cards
    self.cards += info["cards"]
KeyError: 'cards'

I used a regex to delete all the IDs in my files to see if the this problem was with the IDs in my notes. And it was 👍 

The problem may be because there was a note I deleted the card in Anki, but not the text file ID. (if this is a problem, I think there should be a better error handling with this)

**Comment by ddfonseca** [comment]
> The problem may be because there was a note I deleted the card in Anki, but not the text file ID. (if this is a problem, I think there should be a better error handling with this)

Yes, that occur to me too. I need to DELETE on Obsidian OR I just delete the ID note that is related to the card if I have deleted on Anki.

**Comment by Pseudonium** [comment]
Yeah, that is how deletion works at the moment. What I could potentially do is some sort of "compare note ids from Obsidian to note ids from Anki, see where there are problems, mark this in the markdown file". That's probably more useful than just throwing an error!

**Comment by Pseudonium** [comment]
Yep, I've fixed this with my latest commit! The script will now print a warning if a note in Obsidian doesn't exist in Anki, referencing both the problematic ID and the file with the problematic note. And it'll just pass over that note rather than throwing an error that stops execution entirely! Expect to see this soon.
