### ISSUE TITLE
Cloze Regex error when more than 1 capture group

### ISSUE THREAD

**Issue by BrayanDSO** [Pseudonium/Obsidian_to_Anki#78]
The regex guide says:
> You need to have as many capture groups in your regexp as there are fields in the note type - the 1st capture group becomes the 1st field, the 2nd becomes the 2nd field etc

If I have more than 1 capture group in the custom regex set in the config file, it only adds the first one to the card. The other capture groups aren't added to the card.

My default Cloze note type has 3 fields.

**Comment by BrayanDSO** [comment]
It would be good to use custom regex in any custom note type

**Comment by ddfonseca** [comment]
You didn't post your regex to see any errors. But here is mine which has 3 fields too:
`Cloze (Hide all) = ^T: ((?:[^\n][\n]?)+)\n+E: ((?:[^\n][\n]?)+)\n+H: ((?:[^\n][\n]?)+)`

So, if I write:
"T: Here are some {Cloze}
And more {cloze}
E: Extra
H: yes."

It will capture the Text Field, Extra Field and Hide others on back Field. But, You need to write the three fields, even if it is optional. You can, of course, write just some whitespace to fill the gaps.

**Comment by BrayanDSO** [comment]
This is what I put in the config file
```
Cloze = ((?:[^\n][\n]?)+:{3}\n+(?:[^\n][\n]?)+)(?:\n---\n)?(.+)?
```

An example from my files:
```
Quais as células da glia?:::
- **S**: {[[Células de Schwann|Schwann]]}
- **O**: {[[Oligodendrócitos]]}
- **S**: {[[Células satélite|Satélite]]}
- **M**: {[[Micróglia]]}
- **A**: {[[Astrócitos]]}
- **E**: {[[Células ependimárias]]}

---
Extra text
```
As I don't always use the extra field, the second capture group is optional. The "Extra text" should be at the second field in my Cloze note type, but it isn't added at all.


A question, have you put your regex directly in the config file? If so, how? The current documentation isn't very clear. (The regex I'm talking about ↓) 
```
Cloze (Hide all) = ^T: ((?:[^\n][\n]?)+)\n+E: ((?:[^\n][\n]?)+)\n+H: ((?:[^\n][\n]?)+)
```

**Comment by BrayanDSO** [comment]
And I didn't specified any note-type in my file

**Comment by BrayanDSO** [comment]
> A question, have you put your regex directly in the config file? If so, how? The current documentation isn't very clear. (The regex I'm talking about ↓)
> 
> ```
> Cloze (Hide all) = ^T: ((?:[^\n][\n]?)+)\n+E: ((?:[^\n][\n]?)+)\n+H: ((?:[^\n][\n]?)+)
> ```

Oh my. I always ran the script directly to process a folder, it never build the configs with all options. I just tried now and it appeared. Didn't know of this. Nevermind.
But the script still should process the Cloze fields normally

**Comment by BrayanDSO** [comment]
Found the error. 
The config file needs to be update when a new field is updated, not only when a new note type is added (as in the documentation).
As my note was ran by Regex, I haven't thought of this

**Comment by ddfonseca** [comment]
Nice!

**Comment by dummifiedme** [comment]
> This is what I put in the config file
> 
> ```
> Cloze = ((?:[^\n][\n]?)+:{3}\n+(?:[^\n][\n]?)+)(?:\n---\n)?(.+)?
> ```

@BrayanDSO. I need something like this, the extra field. But I would also like to use `==Cloze==` format. Is it possible? Can you help out?
