### ISSUE TITLE
Cloze deletion not working on some cases

### ISSUE THREAD

**Issue by yzdeng** [Pseudonium/Obsidian_to_Anki#81]
1. 
![image](https://user-images.githubusercontent.com/52304960/96360059-e6f57f00-114b-11eb-9b67-d6be254d112e.png)
This line should not be detected as a card, but it was detected as a cloze.
![image](https://user-images.githubusercontent.com/52304960/96360078-11dfd300-114c-11eb-80d7-6f4d9dbf543e.png)
Similar things could happen to a list in markdown file like this one below:
![image](https://user-images.githubusercontent.com/52304960/96360151-d98cc480-114c-11eb-9ce2-f1c28455eb2d.png)
thus i get a lot of empty card in my queue.
2.
![image](https://user-images.githubusercontent.com/52304960/96360093-2fad3800-114c-11eb-941a-2b130a7b39eb.png)
This line is a cloze, but the "c1|" is not translated into "c1::" and the two dollar sign in between is not into "\\(" or "\\)".
![image](https://user-images.githubusercontent.com/52304960/96360103-4a7fac80-114c-11eb-9dbf-dbdbbf37008a.png)

**Comment by mullerrwd** [comment]
I can confirm this issue. The regex provided will also capture placeholders from the template functionality. E.g:
```
---
   - Tag:
   - Sources:
   - Created at: {{date}}
   - Related: 
---
```

**Comment by Pseudonium** [comment]
@yzdeng Hmm, does that math actually render? At least in Obsidian it doesn't - you can't have a space immediately before or after the dollar sign. So I'd say that's expected behaviour? What's happening is that it has a larger 'math block' that includes the {c1, and the script is trained to ignore curly braces in math blocks.

**Comment by Pseudonium** [comment]
@mullerrwd That's a separate issue, but one I hadn't thought about. What I could do is, for each file, compile some sections that should be ignored when checking for cloze deletions - the frontmatter would be one of them. I'll see if I can fix this...

**Comment by Pseudonium** [comment]
@mullerrwd Yep, managed to add this into latest development version of script, so it doesn't add clozes from those templates! I'll close this once the new version releases.
