### ISSUE TITLE
Pasted images not showing in Anki

### ISSUE THREAD

**Issue by uuuser-name** [Pseudonium/Obsidian_to_Anki#84]
When I paste an image in Obsidian, the image doesn't show up in Anki. Only the wiki image link does ("![[image.jpg]]").
Tried using images from internet (copy-paste and drag-and-drop), and local images.

Pasted image in Obsidian (Edit mode)
![pasted image in obsidian edit mode](https://user-images.githubusercontent.com/57158541/97334904-8833b200-187d-11eb-9811-33eeb753d303.png)

Pasted image in Obsidian (Preview mode), the image shows up
![pasted image in obsidian preview mode](https://user-images.githubusercontent.com/57158541/97335006-a3062680-187d-11eb-93c1-d13b9a34f881.png)

Pasted image not showing up in Anki (during review)
![pasted image not showing up in anki review](https://user-images.githubusercontent.com/57158541/97334718-57537d00-187d-11eb-9df7-2366ae2614c1.png)

Pasted image not showing up in Anki (in the browser)
![pasted image not showing up in anki browser](https://user-images.githubusercontent.com/57158541/97335137-c5983f80-187d-11eb-8755-69234988d8b1.png)

On Windows 10 Pro 1903
Using Python 3.7.0 (because the script crashes with older versions because of dependency problems)
Using the remnote syntax + custom syntax [3 colons = Basic (and reversed)] (tested with the proposed syntax, doesn't work either)

**Comment by Raagaception** [comment]
You need to use the standard markdown syntax for image embeds!
https://github.com/Pseudonium/Obsidian_to_Anki#image-formatting

**Comment by uuuser-name** [comment]
> You need to use the standard markdown syntax for image embeds!
> https://github.com/Pseudonium/Obsidian_to_Anki#image-formatting

Oh, thanks a lot. Solved.
For those struggling with this issue, you need to activate the "Use Markdown links" option in Settings/Editor.
