### ISSUE TITLE
Error when running the script: 

### ISSUE THREAD

**Issue by uuuser-name** [Pseudonium/Obsidian_to_Anki#87]
Error when running the script. The script doesn't add the cards to Anki.

Note that the image "Pasted image 2020201028224417.png" does exist.
Edit: if I delete the aforementioned image, the script continues to run until the next file containing an image, where it produces the same error.

On Windows 10 Pro 1903
Using Python 3.7.0, same with Python 3.8.5
Using the remnote syntax + custom syntax [3 colons = Basic (and reversed)].

```Traceback (most recent call last):
  File ".\obsidian_to_anki.py", line 1561, in <module>
    main()
  File ".\obsidian_to_anki.py", line 187, in main
    App()
  File ".\obsidian_to_anki.py", line 881, in __init__
    os.getcwd(), regex=args.regex
  File ".\obsidian_to_anki.py", line 1441, in __init__
    file.scan_file()
  File ".\obsidian_to_anki.py", line 1311, in scan_file
    self.search(note_type, regexp)
  File ".\obsidian_to_anki.py", line 1373, in search
    self.target_deck, url=self.url
  File ".\obsidian_to_anki.py", line 625, in parse
    template["fields"] = self.fields
  File ".\obsidian_to_anki.py", line 617, in fields
    for key, value in fields.items()
  File ".\obsidian_to_anki.py", line 617, in <dictcomp>
    for key, value in fields.items()
  File ".\obsidian_to_anki.py", line 395, in format
    FormatConverter.get_images(note_text)
  File ".\obsidian_to_anki.py", line 328, in get_images
    MEDIA[filename] = file_encode(path)
  File ".\obsidian_to_anki.py", line 104, in file_encode
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'attachments/Pasted%20image%2020201028224417.png' ```

**Comment by dummifiedme** [comment]
I am getting the same error, though I am not even using any images. I tried running on the test file provided here.

**Comment by uuuser-name** [comment]
Found out!

It turns out the spaces, translated to %20 by Obsidian in the in-links, cause the error. I guess the script searches for *literal* "%20" in the filenames, while there are only spaces.

Managed it by creating a script that changes the spaces of every image filename in my attachment directory to underscores. But now I have to change the in-file links to these images manually.

So, the problem's origin is found, but I don't think the issue is closed . The script probably isn't supposed to act like that. It should be easy to make the script consider the "%20" as spaces in filenames.

**Comment by Pseudonium** [comment]
Yes, this has been a bug that others have reported - I didn't realise that the markdown standard included %20 in image links! And as you say, shouldn't be too hard to fix this - will do soon.

**Comment by Pseudonium** [comment]
Yep, have fixed this in one of my recent commits! Expect to see this soon.
