### ISSUE TITLE
Field values are being clubbed into a previous field.

### ISSUE THREAD

**Issue by twisp007** [Pseudonium/Obsidian_to_Anki#89]
Example Markdown:

```
TARGET DECK
Vocab Deck
FILE TAGS
cefr-level:B2
START
clozenew
absorb
definition:<div class=defBox><div class=posDiv><span>verb</span></div><div class=defDiv><div class=defTextInfo></div><div class=defText>{{c1::If something absorbs a liquid, gas, or other substance, it soaks it up or takes it in.}}</div><div class=defEgText><div>Plants absorb carbon dioxide from the air and moisture from the soil.</div><div>Refined sugars are absorbed into the bloodstream very quickly.</div></div></div></div>
inflections:<span>absorbs</span><span>absorbing</span><span>absorbed</span>
cefr-level:B2
example-bank:
IPA:
END
```

Now all the field values after "inflections" are being inserted into the "inflections" field itself. Fields after "inflections" remain empty.

**Comment by twisp007** [comment]
Okay, I think I know where problem is.

The config file contains notes and the fields it contained. If a field is deleted or renames it is not properly reflected as in the the old field name is not removed. 

Also are spaces in field names supported?

**Comment by Pseudonium** [comment]
I see - you know I think I should probably remove this whole 'note substitutions/field substitutions' feature. It clutters the config file needlessly, runs into those issues as you said, and could easily be achieved by just renaming the note type or field name in Anki. Hopefully that'll resolve this issue.

**Comment by Pseudonium** [comment]
Yep, have removed substitutions as a feature, and in fact you should no longer need to 'update' the config file. I should probably update the docs now...
