### ISSUE TITLE
Support Remnote multi-line card and list card syntax

### ISSUE THREAD

**Issue by ghost** [Pseudonium/Obsidian_to_Anki#90]
Remnote can create cards not only single-line cards denoted with a double colon `::` but also multi-line cards with a triple colon `:::` and list cards `::1`. 

Support for this will be useful for those that structure their Obsidian notes using Remnote syntax with the ability to export to both Anki and Remnote if the situation arises.

See: https://www.remnote.io/documentation/DbrajFGebhyrKHGYA for more info.

**Comment by mifegui** [comment]
With this regex as Basic
`^((?:(?=(?:[^\n][\n]?)+:::)[^\n:][\n]?|(?!^(?:[^\n][\n]?)+:::)[^\n])+)(?<![0-9]):::?((?:(?<=:::)(?:[^\n][\n]?)+|(?<!:::)[^\n])+)`
you can match both single-line cards and multi-line cards ([see here](https://regex101.com/r/mptJ17/2/))

**Comment by dummifiedme** [comment]
@mifegui This seems cool. Is there a way to add ::1 listed type too?

**Comment by Pseudonium** [comment]
@dummifiedme Thing is that's not a default type in Anki in the first place! Though if you do have your own list type it shouldn't be too hard to make a regex.
