### ISSUE TITLE
The Obsidian Plugin API is available

### ISSUE THREAD

**Issue by uuuser-name** [Pseudonium/Obsidian_to_Anki#92]
This isn't an issue, this is an announcement, as @Pseudonium wrote that [some features](https://trello.com/b/6MXEizGg/obsidiantoanki) were to be delayed until an official API was available.
API available [here](https://github.com/obsidianmd/obsidian-api), announced in the [0.9.7 release](https://forum.obsidian.md/t/obsidian-release-v0-9-7/7628).

**Comment by AuTa** [comment]
It might be possible to design a sync plugin without affecting the md file.

**Comment by Pseudonium** [comment]
Yep, have been busy up until now, I think I'll try and see whether I can implement this as a plugin soon.
