### ISSUE TITLE
Request for Custom Syntax

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#96]
I am using your Q/A and cloze regex, I would like a small alteration.
I want a card to end whenever there is a double line break (in both the cases).

```
Q: This is a Question
A: This is Answer Line 1

This is Answer line 2.

This is Answer line 3


This is not in answer.

```

Similarly, for cloze cards, the card will end whenever there is a double line break.

Is it possible? :)

**Comment by mullerrwd** [comment]
I assume you mean triple line break, or two empty lines.

Try: 
```regex
^Q: ((?:[^\n][\n]?)+)\n+A: ([\s\S]*?(?=\n{3,}))
```

You will have to remember to insert two empty lines after a QA at the end of the file. This will not be captured:
```
Q: This is a Question
A: This is Answer Line 1

This is Answer line 2.

This is Answer line 3
[EOF]
```
This will:
```
Q: This is a Question
A: This is Answer Line 1

This is Answer line 2.

This is Answer line 3


[EOF]
```

**Comment by dummifiedme** [comment]
Thanks, this is what I needed :)

**Comment by Pseudonium** [comment]
Thanks for resolving this for me @mullerrwd !
