### ISSUE TITLE
'TARGET DECK' line isn't excluded from the note.

### ISSUE THREAD

**Issue by dummifiedme** [Pseudonium/Obsidian_to_Anki#98]
I find that if the TARGET DECK line is placed at the end of the note, it is not omitted from the note in ANKI.
It shouldn't be so, right?

**Comment by mullerrwd** [comment]
The `TARGET DECK` should not be omitted in any case. You can place the `TARGET DECK` anywhere in you note. However, only the first target deck definition on the following line is used.

**Comment by dummifiedme** [comment]
I meant, if I keep TARGET DECK at the bottom of my page, it gets included
in the last card of the page. The cards go to the right deck though.

**Comment by mullerrwd** [comment]
Ok clear. I do not seem to have this Issue. I do, however, have an empty line before and after. And I use custom regex, for cloze and QA format notes.

**Comment by Pseudonium** [comment]
Hmm, why would you have TARGET DECK at the end of your file in the first place? You can omit it, it'll just use the default deck provided in the config file.

**Comment by dummifiedme** [comment]
> Hmm, why would you have TARGET DECK at the end of your file in the first place? You can omit it, it'll just use the default deck provided in the config file.

Yes I do know that, but in my use I need to have multiple decks. I am studying varying courses and sometimes I need to review separately. I know Anki users prefer to have single deck with tags and then create filtered decks for the purpose of custom study, which is fine. I myself am going in that direction since this error. But still, this error exists. 😅

**Comment by Pseudonium** [comment]
I'm still not getting it - so do you have TARGET DECK at the end of your file with no specified deck following? Or is that a deck is specified but this error still persists?

You might want to try spacing out the TARGET DECK line from the flashcard that's causing this bug.

**Comment by dummifiedme** [comment]
The TARGET DECK line I have specified at the end of file. The note gets added to the right deck as ai have specified, but the “TARGET DECK” is included in my note in Anki. I mean, those two words are part of my note in Anki which shouldn’t be the case

**Comment by Pseudonium** [comment]
I'd recommend separating that section by a newline, especially if you're using a paragraph regex

**Comment by dummifiedme** [comment]
I should close this issue. I have moved to include the deck names in the YAML itself. :)

**Comment by dummifiedme** [comment]
I should close this issue. I have moved to include the deck names in the YAML itself. :)
