### ISSUE TITLE
[Solved] Issues installing on Ubuntu 20.04

### ISSUE THREAD

**Issue by mullerrwd** [Pseudonium/Obsidian_to_Anki#99]
I am leaving this here for future reference and for others running into issues whilst trying to install `Obsidian_to_Anki` on `Ubuntu 20.04`. 

The issues were:
- missing pip3
- errors installing wxpython

The Ubuntu 20.04 distro now comes with python3 (3.8.5), however pip3 is missing. Install:
```bash
sudo apt update
sudo apt install -y python3-pip
```

Thenm, to solve the wxpython install error:
```
sudo apt install -y libgtk-3-dev python-wxgtk3.0
```
[Optional ] The above should suffice. If you still receive an error during install of `wxpython` it may be necessary to install the following dependencies below as well. Be sure to check the error logs.
```bash
sudo apt install -y python3-wxgtk4.0 python3-wxgtk-webview4.0 python3-wxgtk-media4.0​
```
Running the install script should now finish succesfully:
```bash
python3 obstoanki_setup.py
```

**Comment by Pseudonium** [comment]
Thanks for this! I'll add this to the 'technical' part of the docs.
